### ISSUE TITLE
Generate sourcemaps for compiled scripts

### ISSUE THREAD

**Issue by bendavis78** [guybedford/es-module-shims#100]
Error messages in the console are reporting the wrong line number due to scripts being compiled together with others (eg, when --polyfill-node is used). A sourcemap should be generated alongside any modules that deviate from their original source.

**Comment by guybedford** [comment]
Sounds like you are using a dev server here perhaps? Did you mean to post this to that project?

**Comment by bendavis78** [comment]
Oops, sorry wrong project!!
