### ISSUE TITLE
[feature-request]: Add option to exclude url patterns from the cache

### ISSUE THREAD

**Issue by ifiokjr** [guybedford/es-module-shims#105]
### Description

It'd be nice to have the ability to exclude certain URL patterns from being cached.

```ts
importShim.skipRegistry = /^\/__internal__\.*/
```

I'm using the `importShim.fetch` to pre-process imports, but in my case I want to always run the pre-process step for specified URL patterns since content can be dynamically updated.

I'm happy to work on this if you think it would be a valuable contribution.

**Comment by guybedford** [comment]
The problem with this feature as designed is that it won't be possible to share *instance state* between modules, which is strictly speaking a required semantic of modules implementations.

Are you sure you need this to apply to loads on the same page, or just to ensure refreshes don't hit the cache?

Otherwise perhaps we should just have a `skipFetchHook` hook instead which uses the default `fetch` for those modules?

**Comment by ifiokjr** [comment]
It's for a `repl` application where every edit by the user is intercepted and transpiled by the `importShim.fetch` hook. `es-module-shims` provides the browser support but also some really useful hooks to make this possible.

Without adding this feature I could possible use `fetch`, but this would require setting up a service worker to intercept the requests and figure out how to pass messages between the service worker and main dom thread.

I'm already working with a forked version locally to implement the behaviour and thought it might be useful for others.

**Comment by ifiokjr** [comment]
> perhaps we should just have a `skipFetchHook` hook instead which uses the default fetch for those modules

I've just reread your comment and I'm looking for an `alwaysPreprocess` flag more than a `skipFetchHook`.

Also, a simpler workaround from my end, which doesn't require any changes to this package would be to append a unique hash to the requested URL based on the content being processed,

**Comment by guybedford** [comment]
So it's more for hot reloading workflows? Are you transpiling from typescript?

Yes in native modules browsers typically hashing is needed for these workflows, but it does create some complexity.

**Comment by guybedford** [comment]
There are no plans to currently implement this.
