### ISSUE TITLE
modules are executed two or three times

### ISSUE THREAD

**Issue by chase-moskal** [guybedford/es-module-shims#111]
i noticed that es-module-shims v0.8.0 seems to be redundantly executing my modules two or three times?

[codepen example](https://codepen.io/ChaseMoskal/pen/RwGmxMa)
```html
<script>
  let count = 1
</script>

<script type="module-shim">
  console.log(count++)
</script>

<script src="https://unpkg.com/es-module-shims@0.8.0/dist/es-module-shims.js"></script>
```

console says
```
1
2
3
```

but sometimes it's only executes twice

i wonder what could be going on?

&nbsp; :wave: chase

**Comment by chase-moskal** [comment]
it appears that the issue does not reproduce for external scripts, ie, the following module executes one time

```html
<script type="module-shim" src="./demo.js"></script>
```

**Comment by guybedford** [comment]
Thanks for posting Chase, fixed in https://github.com/guybedford/es-module-shims/pull/112.
