### ISSUE TITLE
Using WASM Causes Content Security Policy Errors

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [guybedford/es-module-shims#114]
Is there any alternative to using the shim without WebAssembly, as the only way to use the shim when your site uses CSP is to enable `unsafe-eval` which is a bad idea security-wise?

**Comment by guybedford** [comment]
I would recommend [SystemJS](https://github.com/systemjs/systemjs) for this use case, as it is designed around the CSP-compatible System module format.

**Comment by SamuelJohnsonMedia** [comment]
Unfortunately I dont like the way i have to write code that is then incompatible with normal esmodule/importmap support.

Your shim was perfect without requiring any code changes, its just unfortunately chromium does not handle WASM nicely with CSP ... hopefully that will improve.

Thanks for replying.

**Comment by guybedford** [comment]
@SamuelJohnsonMedia right, yes it's an approach that inherently relies on unsafe eval at its root for rewriting the source specifiers. Similarly SystemJS was designed from the ground up to not require unsafe eval.
