### ISSUE TITLE
processScript is generating invalid URL

### ISSUE THREAD

**Issue by gingur** [guybedford/es-module-shims#115]
When running an inline `module-shim` script on a modern browser, the `processScript` is generating a URL `${pageBaseUrl}?${id++}` that `topLevelLoad` is [trying to load](https://github.com/guybedford/es-module-shims/blob/master/src/es-module-shims.js#L34-L37) instead of returning the source,

**Comment by guybedford** [comment]
@gingur yes, that is how we handle the inline script tags, by assigning them a URL into the registry. What issue are you getting here?

**Comment by gingur** [comment]
It tries to load that url which is just a request to the page, so it returns text/html and blows up, never using the source provided. Using latest firefox to test.

**Comment by guybedford** [comment]
@gingur ah right, thanks for pointing out the line here as well - I've added a fix in https://github.com/guybedford/es-module-shims/commit/3ac57de538a2c6f71e08a90b154b1b05bd15061c, will release this soon.

**Comment by guybedford** [comment]
Fix released in 0.10.2.
