### ISSUE TITLE
`Shim Mode` no longer working in Chrome/Edge 89

### ISSUE THREAD

**Issue by Julien-Marcou** [guybedford/es-module-shims#117]
## Bug

Since Chrome/Edge 89, using `Shim Mode` (es-module-shims `v0.10.2`) to import modules no longer works :

## Code

Using the `unicode-emoji-picker` package from NPM

```html
<unicode-emoji-picker></unicode-emoji-picker>

<script async src="https://unpkg.com/es-module-shims@latest/dist/es-module-shims.js"></script>
<script type="importmap-shim">
  {
    "imports": {
      "scrollable-component": "/path-to-node-modules/scrollable-component/index.js",
      "unicode-emoji": "/path-to-node-modules/unicode-emoji/index.js",
      "unicode-emoji-picker": "/path-to-node-modules/unicode-emoji-picker/index.js"
    }
  }
</script>
<script type="module-shim" src="/path-to-node-modules/unicode-emoji-picker/index.js"></script>
```

## Actual behavior

I got the following error in Chrome/Edge :
`Uncaught (in promise) TypeError: Failed to resolve module specifier "scrollable-component". Relative references must start with either "/", "./", or "../".`

And the code is not working.

In Firefox everything is working correctly.

## Expected behavior

It should work in Chrome/Edge/Firefox.

## Additional information

Using the `Polyfill Mode` actually makes it work everywhere :

```html
<script async src="https://unpkg.com/es-module-shims@latest/dist/es-module-shims.js"></script>
<script type="importmap">
  {
    "imports": {
      "scrollable-component": "/path-to-node-modules/scrollable-component/index.js",
      "unicode-emoji": "/path-to-node-modules/unicode-emoji/index.js",
      "unicode-emoji-picker": "/path-to-node-modules/unicode-emoji-picker/index.js"
    }
  }
</script>
<script type="module" src="/path-to-node-modules/unicode-emoji-picker/index.js"></script>
```

But then I got the following error in Firefox :
`Uncaught TypeError: Error resolving module specifier “scrollable-component”. Relative module specifiers must start with “./”, “../” or “/”.`

Which is expected as specified in the [README](https://github.com/guybedford/es-module-shims/blob/master/README.md#polyfill-mode), and even though it's working in Firefox, I'd rather not have this error by using the `Shim Mode` as I was doing for months (until Firefox can properly works with the `Polyfill Mode`).

(You can actually see the live `Polyfill Mode` in use here : https://emoji.julien-marcou.fr/)

So I'm not sure, should I migrate my code to now use the `Polyfill Mode` instead of the `Shim Mode` ? Am I doing something wrong with the `Shim Mode` ?

**Comment by guybedford** [comment]
Thanks for posting - yes this was a regression. Fixed in 0.10.3.
