### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by keroiber** [guybedford/es-module-shims#121]
Hello @guybedford, package.json states that this package is distributed under the MIT license, but the license file is missing. Would you mind to add one (see e.g. [choosealicense.com](https://choosealicense.com/licenses/mit/))?

**Comment by guybedford** [comment]
Thanks for noticing this - I've checked it in at https://github.com/guybedford/es-module-shims/commit/2d7ce60c2fe3ecbc73f3628fd16821d3285e9798.
