### ISSUE TITLE
Errors in FF and Safari (non-polyfilled module is imported?)

### ISSUE THREAD

**Issue by vovacodes** [guybedford/es-module-shims#129]
I'm running into some weird errors with es-module-shims on this page (reproducible in FF and Safari): https://deploy-preview-51--romantic-wiles-3910cf.netlify.app/ 
I looks like the original (non-processed by the lexer) module is getting imported somewhere in the chain.

![image](https://user-images.githubusercontent.com/1524432/120767826-ddbef400-c51b-11eb-96c9-003d150a061b.png)

**Comment by guybedford** [comment]
@vovacodes did you mean to be running in shim mode here? Which module is executing that you would not have expected to be executing?

**Comment by vovacodes** [comment]
FocusManager.js is being evaluated it looks like. I expect it to run in the polyfill mode here

**Comment by guybedford** [comment]
I see, agreed this is a bug in polyfill mode, looking into it.

**Comment by guybedford** [comment]
@vovacodes is there perhaps a cycle in play with `FocusManager.js`? If so, that could be the reason the check algorithm is breaking down.

**Comment by guybedford** [comment]
Do you think you could host a version of this running the debug build of ES module shims? That would help a lot to investigate how this is happening in the registry.

**Comment by guybedford** [comment]
Fixed in #130.
