### ISSUE TITLE
Shim requires with FireFox CSP "script-src 'unsafe-inline' data: blob:"

### ISSUE THREAD

**Issue by ralfbecker** [guybedford/es-module-shims#132]
[EGroupware](https://github.com/EGroupware/egroupware/tree/new-js-loader) a PHP and JavaScript using open-source groupware suite uses Content-Security-Policy with (beside others) forbidding for script-src unsafe-inline data: and blob:.

We're in the process of replacing our old JS loading (based on LAB.js) with native JS modules and importmap, without further tooling. The plan was to use your shim for FireFox and Safari, until they start supporting importmap native.

**Unfortunately an undocumented requirement of the shim seems to be to have no (or a very lax) CSP.**

For the importmap tag itself I use a nonce, but the shim generates own script tags without nonce or the ability to set a nonce.

Is there a way to use the shim together with a reasonable CSP, or could it be modified to do so?
My tries to modify the shim to set a nonce on it's generated script tags were not successful :(

Ralf

**Comment by ralfbecker** [comment]
Forgot to write that I use your [Polyfill mode](https://github.com/guybedford/es-module-shims#polyfill-mode), in case that matters.

**Comment by guybedford** [comment]
It is a known limitation of this project that CSP is not supported, and this is listed at https://github.com/guybedford/es-module-shims#implementation-details.

SystemJS provides an alternative workflow for supporting import maps with CSP support, and the SystemJS module format is exactly the way it is to support CSP.
