### ISSUE TITLE
Resolver hook

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-shims#143]
It could be useful to expose a resolver API via:

```js
globalThis.esmsInitOptions = {
  resolve: (specifier, parent, defaultResolve) => defaultResolve(specifier, parent)
}
```

where `defaultResolve` is the normal resolve implementation of URL and import map resolution.

This would make it easy to eg hook stripping querystrings:

```js
globalThis.esmsInitOptions = {
  resolve: (specifier, parent, defaultResolve) => defaultResolve(specifier.split('?')[0], parent)
}
```

**Comment by zhoukekestar** [comment]
Any update on this feature ? It seems simple to implement and very useful.

**Comment by guybedford** [comment]
@zhoukekestar if you're interested in working on this a PR would be great.

**Comment by guybedford** [comment]
Released and implemented in https://github.com/guybedford/es-module-shims#resolve-hook by @zhoukekestar.
