### ISSUE TITLE
Exception raised about fetchCache in 0.12.3

### ISSUE THREAD

**Issue by dhh** [guybedford/es-module-shims#151]
Just tried 0.12.3 to see if I could do away with the Chrome aborting hack. I see this raised in Chrome 92:

<img width="551" alt="Screen Shot 2021-08-18 at 21 39 46" src="https://user-images.githubusercontent.com/2741/129961702-1036a567-b055-4f80-a16a-aec96b4bafb9.png">

Referring to:

<img width="492" alt="Screen Shot 2021-08-18 at 21 42 03" src="https://user-images.githubusercontent.com/2741/129961851-1c26a21f-26b9-4b33-890a-512b10c997a8.png">

**Comment by guybedford** [comment]
This was a good catch, thanks, fixed in 0.12.4.
