### ISSUE TITLE
Support clear module cache in Single Page Application

### ISSUE THREAD

**Issue by zhoukekestar** [guybedford/es-module-shims#153]
Support clear module cache so we can reload the whole modules if need.

Here is the online demo: https://codesandbox.io/s/vigilant-cache-eue89?file=/index.html

In page 1, we load React Component with react 16. Then switch to page 2, we will get react 321 error because we have react copies. Switch to Page 3, clear module cache before loading page, so we can render it without error.

The implement is simple, just add code:

```js
importShim.clear = function() {
  registry = {};
  importMap = { imports: {}, scopes: {} };
}
```

If you think it is reasonable, I can write a PR for this.

**Comment by guybedford** [comment]
This won’t work when running in polyfill mode unfortunately.

In general, the way to achieve isolation / reinstantiatiin is to create an
iframe and run the execution in there then create a new iframe for the next
loading cycle to get this same functionality.

**Comment by zhoukekestar** [comment]
Okay, got it. I have to implement it privately if we need this.

**Comment by guybedford** [comment]
Yes ideally we should always take the browser APIs on their own as far as possible before implementing custom mechanisms here, since the goal is as much as possible to track browser standards.

**Comment by guybedford** [comment]
If a clear API followed a draft spec for an approach that could work in native browsers then the story would be different.... and there's definitely scope to propose such specs!

**Comment by zhoukekestar** [comment]
Yes, I understand, so the private implement will be better for this open-source project.

The browser's JS runtime sandbox and the customElements.define can't reload too, so... It's Okay.

**Comment by guybedford** [comment]
@zhoukekestar the iframe technique is used in JSPM Sandbox for example and works very well in my experience. It's fairly simple to work out, but if you need a code sample do let me know.

**Comment by zhoukekestar** [comment]
USE single HTML for every router instead of SPA maybe our best choice for NOW. 😂

**Comment by guybedford** [comment]
@zhoukekestar it's very straightforward to implement a `runInIframeAndReturnModuleInstance(moduleSpecifier)` function that can work alongside a `resetIframe` function. If that doesn't fit your use case, I'd be interested to hear how.

**Comment by zhoukekestar** [comment]
Iframe is a perfect JS sandbox (like util libs lodash), but it can't interactive with the parent's DOM ( some React component or WebComponent ). I think it's not easy to do.

**Comment by guybedford** [comment]
@zhoukekestar so if the code does not touch the global through the global but only manipulates the dom through injection then it can work that way since you can execute the modules in the iframe, then get back the final module to the top frame. So if the code is like:

```js
import { querySelector } from 'domutils';
export function manipulateDom () {
  querySelector('body').innerHTML = 'asdf';
}
```

then you can run the module in the iframe, get the export back to the main frame, and run the function. But agreed the global attachments are an issue here and exactly where realms / compatment APIs will hopefully bridge this gap in future.

**Comment by zhoukekestar** [comment]
Seems a GREAT idea, like a `worker` sandbox with `domutils`.
Worth trying this in some situations.
