### ISSUE TITLE
"Failed to load module script" exception in 0.12.5

### ISSUE THREAD

**Issue by dhh** [guybedford/es-module-shims#157]
Just tried out 0.12.5 and saw this error that's new:

<img width="1025" alt="Screen Shot 2021-08-20 at 22 00 26" src="https://user-images.githubusercontent.com/2741/130287634-ec5e8831-1d65-4de7-8403-fabdde9590bb.png">
 
Chrome 92.

**Comment by guybedford** [comment]
Thanks, fixed in 0.12.6, and added full Chrome CI in https://github.com/guybedford/es-module-shims/pull/160 to avoid cases like this in future.
