### ISSUE TITLE
Plan of action when importmaps lands in browsers

### ISSUE THREAD

**Issue by Hypercubed** [guybedford/es-module-shims#16]
Apparently import-maps are supported now in chrome (behind a flag).  What's the plan for this module when that moves out?  If this were a pollyfill then it would just work... but as it is will we need to start adding the import-maps twice (`<script type="importmap-shim">` and `<script type="importmap">`)?  Will `es-module-shims` disable if import-maps are native?

**Comment by guybedford** [comment]
I've just added https://github.com/guybedford/es-module-shims/commit/954f2ae345d275932709d452d98213c7cd532400 to note some clarifications around this.

Some JS technique would likely be needed here. If we can work out something reliable it would be really nice to have that to include in the readme here as well.

A detection might look like:

```html
<script>
function supportsImportMaps () {
  let loaded = false;
  document.head.appendChild(Object.assign(document.createElement('script'), {
    type: 'importmap',
    onload () {
      loaded = true;
    }
  });
  return loaded;
}
</script>
```

where a dynamic injection of either project can be used depending on the results of that (and if that works, I haven't tested it).

Better support for dynamic injection of import maps in this project, and handling multiple injections, is tracking in https://github.com/guybedford/es-module-shims/issues/15 too.

**Comment by guybedford** [comment]
Let's continue to track this in https://github.com/guybedford/es-module-shims/issues/29.
