### ISSUE TITLE
On shimmed browsers, all modulepreloads are re-fetched when the HEAD is mutated by Turbo on SPA page changes

### ISSUE THREAD

**Issue by dhh** [guybedford/es-module-shims#163]
Turbo changes pages by copying dom elements around inside the existing document. It seems like this behavior is triggering re-fetching of modulepreload link tags. These tags are fetched from cache, but it's still not without a performance ding at times. Here's an example from Safari:

<img width="1272" alt="Screen Shot 2021-08-24 at 2 21 34 PM" src="https://user-images.githubusercontent.com/2741/130615626-50a642f0-90f5-4a28-bb0c-bf211879ed2d.png">

**Comment by guybedford** [comment]
This should be fixed in 0.12.8 now but please let me know if it isn't.

**Comment by dhh** [comment]
Already tested the patch and it worked 👌
