### ISSUE TITLE
request: clarity on installation in the README

### ISSUE THREAD

**Issue by trusktr** [guybedford/es-module-shims#187]
For example, in what order should things be loaded?

Is this correct?

```html
<head>
  <script async src="https://ga.jspm.io/npm:es-module-shims@0.14.0/dist/es-module-shims.js"></script>
  <script type="importmap">
    {
      "imports": {
        "chai": "/base/test/chai.js",
      }
    }
  </script>
</head>
<body>
  <script src="foo.js" type="module"></script>
</body>
```

What are correct and incorrect ordering and/or script attributes?

In my case, I get these errors:

```
Uncaught TypeError: Error resolving module specifier “chai”. Relative module specifiers must start with “./”, “../” or “/”.
  ...
Uncaught Error: Error: Unable to resolve specifier 'chai' from http://localhost:9876/foo.js (https://ga.jspm.io/npm:es-module-shims@0.14.0/dist/es-module-shims.js:1)
  ...
```

so it seems the `importmap` is not being picked up, but I'm probably doing something wrong, and it's not clear what.

Modules are supposed to run twice in polyfill mode?

**Comment by trusktr** [comment]
ok, it turns out that I **did** get some installation configurations correct, and that was whenever I experienced the `import not found: default` errors that I described in https://github.com/guybedford/es-module-shims/issues/186.

However `es-module-shims` obfuscates the file names by creating blobs and the error messages become unhelpful.

I was able to determine this by first getting up and running in Chrome (which has native importmaps), which then led me to errors in my mapped `/base/test/chai.js` file.

Had I not used a native-importmap-capable browser, I would still be having an incredibly difficult time debugging.

Two things are needed:

- Better documentation on how to install esms (I'm still not sure, now I need to go tinker again in Firefox)
- Better error messages that don't show obfuscated file names

**Comment by guybedford** [comment]
You were doing everything correct. Not using an import maps browser is certainly a disadvantage of these workflows - it's nice to treat es-module-shims as something you just add at the end as part of ensuring backwards compat instead.

Re errors, I've noted that these are browser issues in the other issue.

Any direct suggestions on how the README can improve basic usage welcome.

**Comment by trusktr** [comment]
> it's nice to treat es-module-shims as something you just add at the end as part of ensuring backwards compat instead.

Indeed, now that I got native my importmap setup working in Chrome, it will be easier to enable it for Firefox (instead of starting and debugging in Firefox while shimming).



> Any direct suggestions on how the README can improve basic usage welcome.

I think it would namely be clarification on what to do _and_ what not to do. I'm still not clear on it though. I'll circle back once I circle back to Firefox.
