### ISSUE TITLE
Fallback support or note in documentation

### ISSUE THREAD

**Issue by begrs** [guybedford/es-module-shims#19]
Since fallbacks in import maps are not supported yet, please either implement them or add a note to the Readme to make it obvious to devs that this part of import maps is not supported.

I wanted to use import shims mainly for that purpose so I am a little disappointed that this basic/important feature when working with cdn provided js files is not yet implemented.

best reagards

**Comment by guybedford** [comment]
As specified currently, import maps fallbacks only apply to builtin modules using the `std:` native namespace in the browser itself.

Fetch scheme fallbacks have not been specified, and personally I hope and will strongly argue for them not to be a feature.

So the best we could do to support this right now while remaining spec compliant would be to always treat `"imports": { "x": ["std:x", "/x.js"] }` as resolving `/x.js`.

I'd be glad to take a PR along those lines.

**Comment by guybedford** [comment]
This has been implemented.
