### ISSUE TITLE
File relative paths in package maps.

### ISSUE THREAD

**Issue by MicahZoltu** [guybedford/es-module-shims#2]
`my.domain/foo/bar.html`
```html
<!DOCTYPE html>
<script type='module' src='es-module-shim.js'></script>
<script type='packagemap-shim'>
{
    "packages": {
        "apple": "./index.js"
    }
}
</script>
<script type='module-shim'>
import apple
</script>
```
The above code will try to load `my.domain/foo/apple/index.js`.  If I change it to `/index.js` it will try to load `my.domain/index.js`.

Why is it prefixing the path with the package name?  How do I tell it to not do that?  Is this part of the spec, or a bug in this library?

**Comment by guybedford** [comment]
It's weird, yes, but the way to think of this is `"packages": { "apple": { "main": "./index.js" } }` where the "./" is relative to the package name.

So a `../` is needed to get the expected result.

Luckily it's looking like the new version of the spec won't have this unfortunate feature.

**Comment by MicahZoltu** [comment]
Thanks, I'll eagerly await the updated spec.
