### ISSUE TITLE
Worker test failing in Firefox

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-shims#20]
I was just testing out the Worker feature in Firefox to release this work and unfortunately it seems to be failing there (although passing in Chrome).

//cc @costingeana

**Comment by costingeana** [comment]
I'll fix this asap. My apologies for not testing Worker feature in Firefox.

**Comment by guybedford** [comment]
It seems the Firefox issue is because we don't actually have support for `new Worker('asdf', { type: 'module' })` in Firefox at all.

And the shim is directly relying on this support which is currently only in Chrome it seems.

That's a little concerning as it means the worker shim isn't going to be that reliable unfortunately...

**Comment by costingeana** [comment]
I was afraid that's the cause of the issue. I will a have a closer look and then I will come back with the results.

**Comment by guybedford** [comment]
Ok I've published 0.2.8 with the WorkerShim support now.

Yes, we should carefully check what the browser support looks like here further.

**Comment by costingeana** [comment]
Well, it seems that Firefox 67 supports dynamic module imports (recently added) but it doesn't support yet dynamic module imports in Workers. There is an issue about this subject: https://bugzilla.mozilla.org/show_bug.cgi?id=1540913.

I'll keep digging; I hope I'll find a way to overcome this issue.

**Comment by guybedford** [comment]
We should also check what Safari and Edge do here.

**Comment by guybedford** [comment]
Closing, as I don't think it's possible to get around the lack of dynamic import support in workers.
