### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by zhoukekestar** [guybedford/es-module-shims#202]
I think it's a `es-module-lexer` 's bug as occurred in file `https://unpkg.com/es-module-lexer@0.9.0/dist/lexer.asm.js`

Use `https://unpkg.com/es-module-shims@1.0.4/dist/es-module-shims.wasm.js` will fix it.

Here is the [online Demos](https://codesandbox.io/s/throbbing-haze-7wm2u?file=/wasm.html):

* [https://7wm2u.csb.app/index.html](https://7wm2u.csb.app/index.html)
![image](https://user-images.githubusercontent.com/7157346/135011414-95f6b13d-54b3-4e55-8cd0-d46ec4551677.png)

* [https://7wm2u.csb.app/wasm.html](https://7wm2u.csb.app/wasm.html)
![image](https://user-images.githubusercontent.com/7157346/135011439-2affaedc-730b-40ed-878a-ce57c417bc76.png)

**Comment by guybedford** [comment]
Thanks for the report @zhoukekestar, fixed in https://github.com/guybedford/es-module-shims/pull/203.
