### ISSUE TITLE
Fetch hook property name is wrong in the README

### ISSUE THREAD

**Issue by yuhr** [guybedford/es-module-shims#204]
<https://github.com/guybedford/es-module-shims/tree/1.1.0#fetch-hook>

I was trying to use Shim Mode and `fetch` hook but had no luck until I looked into the source code:

<https://github.com/guybedford/es-module-shims/blob/1.1.0/src/options.js#L25>

Setting `fetch` property has no effect, so please fix the docs to use `fetchHook` instead.

**Comment by guybedford** [comment]
Thanks for reporting - this was actually an issue with the fetch test and a bug that it got renamed to the name used internally. I've added a fix in https://github.com/guybedford/es-module-shims/pull/205.

**Comment by guybedford** [comment]
Fix released in 1.2.0.
