### ISSUE TITLE
Automatic rewriting of new Worker

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-shims#21]
We should be able to support the following replacement in the lexer:

```js
new Worker(...)
```

->

```js
new WorkerShim(...)
```

This would provide comprehensive module worker support, which would be kind of amazing.

**Comment by costingeana** [comment]
@guybedford,  I was wondering if you could do the same for `import(...)` calls, in other words to replace`import(...)` with `importShim(...)` in lexer.

**Comment by guybedford** [comment]
Yes we do already do that. If there’s a case it’s not happening it could be
a bug.

**Comment by costingeana** [comment]
I apologize, I didn't realize that before posting the message (that I deleted after I checked the code once again). In my code I was using directly `importShim`. My bad.

**Comment by guybedford** [comment]
No worries - it's always good to discuss these things. If you think we can add a documentation change to make this sort of thing clearer let me know.

**Comment by guybedford** [comment]
WorkerShim has been removed in https://github.com/guybedford/es-module-shims/pull/84, the reason for this being that support in Firefox etc has not been possible due to a lack of dynamic import.

Open to further techniques in future but we do need to try and offer solutions that are cross-platform.
