### ISSUE TITLE
Checking existing import map before injecting new import map

### ISSUE THREAD

**Issue by lewisl9029** [guybedford/es-module-shims#211]
Hi there! 

I've been trying to iron out some of the edge cases in my react-refresh workflow using es-module-shims's fetch hook. One of these requires injecting new import maps for new files that were added during development. 

To avoid errors (according to the spec, dynamically injected import maps must not override any existing entry) and wasted work, I'd like to be able to only inject new import maps if the files added don't already exist. I could probably hack together something myself by reading the importmap/importmap-shim scripts on the page and merging them, but since es-module-shims already keeps track of the latest import map state, it would be perfect if I could just read from that.

As far as I can tell, es-module-shims doesn't currently expose any global runtime APIs outside of the `importShim` function, so I wanted to get your thoughts/preferences on what this API should look like before I go ahead and try to open a PR. The actual implementation could be as trivial as replacing https://github.com/guybedford/es-module-shims/blob/main/src/es-module-shims.js#L66 with `self.importMap = // ...` so it's accessible globally, but I imagine we'd want some namespacing and/or maybe expose a function instead to better control access to the internal state.

Or maybe you'd prefer to avoid exposing internal import map state altogether? In that case, maybe we could refactor out a few functions for users to call to reuse the same logic that es-module-shim uses to build up our own import map state? Barring that, I'd probably just have to resort to copy pasting that logic from es-module-shims, which tbh isn't the end of the world either.

Let me know which path you'd prefer!

**Comment by lewisl9029** [comment]
Yep that's exactly it!

**Comment by guybedford** [comment]
As much as possible, the starting point for this project is the spec side of things. So implementing behaviours that are non-spec should only ever apply to shim mode for the most part. I'm very hesitant to add anything new to polyfill mode.

In terms of the spec behaviour there are definitely uncertainties:

* Would multiple import maps throw or silently override?
* Perhaps silent overrides can be permitted for import mappings that have not yet been "used"

I tend to think throwing overall is a safer approach to any spec work here though.

Given that, I would try to come at it from the perspective of how you would write your app if this was native HTML. (3) seems to be the only option that follows that. And then having the correct error behaviours likely isn't a blocker to your work anyway.
