### ISSUE TITLE
Use GitHub releases

### ISSUE THREAD

**Issue by jaydenseric** [guybedford/es-module-shims#215]
Can this project please use GitHub releases when new versions are published?

This way we can use the GitHub repo watch feature to be notified of releases.

In the system I'm building, `es-module-shim` is used directly in the HTML template via an async script so no tooling will notify us an update for this "dependency" is available. We're having to manually check npm every few days to see if there is a newer version of `es-module-shims` we should upgrade to.

Also, ideally the changelog entry content for the new version would be included in the GitHub release description, so we can see what's changed right in the email notification without having to lookup the changelog file in the repo.

**Comment by guybedford** [comment]
Now that GitHub has automated release notes generation, this is easy to add and I've gone ahead and posted it for the latest version.

If you're benefitting from my work, sponsorships are very welcome.

**Comment by jaydenseric** [comment]
Thanks, the release notification was great :)

> If you're benefitting from my work

FYI at this time I'm not monetizing your work here in any way; my interest in the project is as part of a new open source web application framework I've been working on (unpaid) for much of the year.

> sponsorships are very welcome

If your personal @guybedford account had GitHub sponsors available I would love to directly reward and publicly acknowledge the great work you're doing. As an individual I'm not very enthusiastic about sponsoring foundations or organizations, but I'll strongly advocate for commercial enterprises I have influence within to do so.

**Comment by guybedford** [comment]
An open source environment of the underpaid demanding high expectations of the similarly underpaid is the main concern for our ecosystem. Understanding and getting past that without simply all falling to the dominant financial forces anyway is the challenge. Good luck with your project!
