### ISSUE TITLE
`sourceMappingURL` and `sourceURL` rewriting breaks my apps

### ISSUE THREAD

**Issue by hronro** [guybedford/es-module-shims#217]
https://github.com/guybedford/es-module-shims/blob/1.3.0/src/es-module-shims.js#L262-L264

I don't think a simple regex replacement is enough, please consider the code below:

```js
// this function usually comes from a bundler runtime
function foo(modulePath){
  bar("// # sourceURL="+modulePath);
}
```

Currently es-module-shims will rewrite this function into invalid syntax.

Perhaps we should parse the whole javascript and only replace `sourceMappingURL` and `sourceURL` in comments? (maybe I'm wrong, but it seems it have already parsed javascript in `es-module-lexer`?)

**Comment by guybedford** [comment]
The sourcemapping regex is supposed to stop on newlines and only detect source map comments at the end of the source.

I've added a possible fix to the regular expression in https://github.com/guybedford/es-module-shims/pull/218 - can you perhaps let me know if that resolves the issue for you?
