### ISSUE TITLE
Dynamic import breaks object identity

### ISSUE THREAD

**Issue by heypiotr** [guybedford/es-module-shims#219]
Minimal repro: [esm-shims-1.3-issue.zip](https://github.com/guybedford/es-module-shims/files/7474462/esm-shims-1.3-issue.zip). Downgrading to 1.2 fixes the issue.

Situation: I've got modules "a.js" and "b.js", import-mapped under "a" and "b" respectively. Both of these modules import an object from "./common.js", and expose it on `window.common_a` and `window.common_b` (just for debugging).

If I do:

```
<script type="module">
import "a";
await import("b");
console.log(window.common_a === window.common_b);
</script>
```

... then in Safari and Firefox (polyfilled import maps), the console.log expression evalautes to false, i.e., the supposedly shared common object actually ends up being different in a and b.

![image](https://user-images.githubusercontent.com/1155764/140308065-7d24f861-e547-4f60-a282-5037f5173273.png)

In Chrome, it works as expected:

![image](https://user-images.githubusercontent.com/1155764/140308096-41d199d3-f0d9-4582-a6f2-7daa5b20d23d.png)

In a real situation, "a" is ReactDOM, "b" is a React component, and "common" is React, which means trouble 😄

**Comment by guybedford** [comment]
Thanks for the clear replication, fix in https://github.com/guybedford/es-module-shims/pull/220.
