### ISSUE TITLE
"Fixing" arbitraily-deep bare import specifiers?

### ISSUE THREAD

**Issue by benfjohnson** [guybedford/es-module-shims#224]
I have what I believe to be a fairly common use-case, but can't seem to find any clear guidance for it.. I'm trying to use ES6 in-browser modules with no additional build tooling/bundlers for a small app. This app has a couple of third party dependencies. A simplified version of my index.html looks as follows:

```
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8"/>
  </head>

  <body>
    <!-- Some basic stuff... -->

    <script type="module">
      // Third party lib, which exposes an esm version of their lib, in addition to the transpiled CommonJS one
      import Messages from "./node_modules/@messageformat/runtime/esm/messages.js";
      // Local script on the filesystem
      import msgData from "./myMessages.js";
      // This does not work, because this index file imports from many other files via a bare import specifier!
      import { createIntl, createIntlCache } from "./node_modules/@formatjs/intl/lib/index.js";

      // do the stuff...
     </script>
  </body>
</html>
```

Because the messages.js file exposed by the @messageformat lib has no imports, I'm able to use it by providing its file extension. I receive an error (as expected) when trying to import the index.js file from FormatJS in the same manner, because it contains bare import specifiers within itself. I tried using the `module` query param from UNPKG (e.g. https://unpkg.com/browse/@formatjs/intl@1.10.5/lib/index.js?module) as I'd heard it can do some fancy resolving of bare specifiers, but I'm either using the query param incorrectly, or it's not working as intended.

My next thought was to use an `importmap` script in conjunction with this library, which got me close (woot!), but I quickly realized the many levels of nested dependencies in the FormatJS lib would mean a massive number of imports specifiers to map.

Is there a simple(ish) solution that can be achieved with this library that would map all bare specifiers, regardless of depth, into their .js equivalent? Any guidance would be very appreciated. 🙂

**Comment by chase-moskal** [comment]
hello. if i'm interpreting your predicament correctly, you're looking for a way to generate an importmap that accounts for sub-dependencies. and i see you are using `node_modules`, so i'd assume you have a `package-lock.json` you can use.

in this case, you might consider using `importly` to generate an import map based on your package-lock file. the resulting import map will include mappings for all sub-dependencies: https://github.com/chase-moskal/importly#readme

**Comment by benfjohnson** [comment]
Thanks for the tip @chase-moskal! I played around with `importly` this morning, and while it does seem to solve the problem of mapping each dependency (and in turn, its dependencies) to the right path within my node_modules folder, it does not seem to solve the issue of those dependencies importing themselves (other local files in the same folder/package) via bare specifiers.

For example, running importly with the `@formatjs/intl` package in my node_modules correctly generates an import map with the values:

```
...
"@formatjs/intl/": "/node_modules/@formatjs/intl/",
"@formatjs/intl": "/node_modules/@formatjs/intl/lib/index.js",
...
```

But, this map does not recognize that the intl/lib/index.js file imports other files from a sub-folder, e.g. `import utils from './src/utils';`. Because this import uses a bare specifier, the import 404s in the browser.

**Comment by chase-moskal** [comment]
@benfjohnson 

okay, i think i know what might be causing this issue here. let's take a close look at the failing import you mentioned

`import utils from './src/utils';`

1. this is not a bare specifier import, it's actually a relative import
2. this import does not include the `.js` extension, which is probably why this is failing with a 404

this same problem happens to me frequently, because most library authors aren't publishing properly modernized modules. nowadays, the `.js` extensions are required for "direct" browser support, but sadly, most library authors are yet unaware of this. the modern best practice is to always include `.js` extensions in all imports -- browsers require the extensions, nodejs is agnostic about them -- so including extensions will maximize support.

to be clear, this problem you're experiencing isn't exactly an issue involving import maps or importly. instead, this problem is happening because the libraries you're using were authored to be consumed by nodejs or by bundlers which mimic node.

**Comment by chase-moskal** [comment]
you know, i wonder if we could make a script that loops through node_modules and inserts `.js` extensions where appropriate. if such a script was placed in a package's `prepare` script, it would run after every `npm install`, and it might work like magic...

**Comment by benfjohnson** [comment]
Thanks, and appreciate the correction on the bare vs. relative terminology. I do think that such a script would resolve this particular issue (I wasn't aware of the `prepare` hook, neat 🙂) but in the meantime I'll mitigate by using a build tool. I'm going to close this issue as I agree that we've moved beyond the scope of the `es-module-shims` lib.

Cheers!

**Comment by guybedford** [comment]
Thanks @chase-moskal for the discussion here. Note that the Node.js ESM semantics are designed such that these workflows work out without needing modification, although CJS still throws a spanner in the works for now. If all the packages were Node.js ESM packages, then the workflow above would always work out consistently, and these invariants are guaranteed by modern Node.js thankfully (short of users using `createRequire` or `process` references of course!).

**Comment by guybedford** [comment]
FWIW just tried this out on generator.jspm.io and it seems like it works out there - https://generator.jspm.io/#U2VjYGBiDs0rySzJSU1hcEjLL8pNLMkq1s/MK8lxMNQzNNUzYHDITS0uTkxPhUjqF5UCleemOhjrGegZAAB/5E+sQQA
