### ISSUE TITLE
Completely new to using shims

### ISSUE THREAD

**Issue by mrwadepro** [guybedford/es-module-shims#226]
I am working on a project that uses es-module-shims and I am importing a node module.

**index.html**
```
    <script type="importmap-shim">
      {
        "imports": {
           "elasticlunr/":"../node_modules/elasticlunr/" 
        }
      }
    </script>
```

**index.js**
```
import elasticlunr from "elasticlunr";
```

I am getting the following error:
```
Unable to resolve specifier 'elasticlunr' 
```

Which, I understand in the READMe that this is a feature. However, it seems my import doesn't actually work at all. I am 100% sure I am missing something any help would be awesome! Thanks

**Comment by guybedford** [comment]
If' you're looking to generate import maps against node_modules, you can try using an import map generator project like JSPM generator to do this, see eg https://github.com/jspm/generator#generating-with-node_modules.

**Comment by mrwadepro** [comment]
> If' you're looking to generate import maps against node_modules, you can try using an import map generator project like JSPM generator to do this, see eg https://github.com/jspm/generator#generating-with-node_modules.



Thanks for this! I get stuck with the same situation when I try to import this,
```
Unable to resolve specifier '@jspm/generator' from http://localhost:8888/web/generate.js
```

How can I overcome this?
@guybedford

**Comment by guybedford** [comment]
@mrwadepro you need to use JSPM generator to generate a map for JSPM generator in turn :) The online version can help bootstrap for you - https://generator.jspm.io/#U2NhYGBkDM0rySzJSU1hcMgqLsjVT0/NSy1KLMkvcjDUM9Az0E1KLUnUMzIEAOGjcqcsAA. Or you can just use that version directly.

**Comment by guybedford** [comment]
(Or run @jspm/generator in Node.js)
