### ISSUE TITLE
importmap failing in Safari 

### ISSUE THREAD

**Issue by georgealways** [guybedford/es-module-shims#242]
Hey there, thanks for this project—sorely needed! I'm getting an error trying to use import maps in Safari (15.1):

![Screen Shot 2021-12-16 at 10 13 15 AM](https://user-images.githubusercontent.com/238907/146397603-ca45a097-5ab7-4e22-9701-874dfeed5f55.png)

The body of the page looks like this:

```html
<script async src="https://unpkg.com/es-module-shims@1.4.1/dist/es-module-shims.js"></script>

<script type="importmap">
{
	"imports":{
		"lil-gui":  "../../dist/lil-gui.esm.js",
		"lil-gui/": "../../"
	}
}
</script>

<script type="module">
import GUI from 'lil-gui';
import './XYController.js';
...
</script>
```

XYController's import looks like this:

```js
import CustomController from 'lil-gui/extras/CustomController.js';
```

Apologies if I'm missing something obvious! -g

**Comment by georgealways** [comment]
Apologies -- the regex was in my code! Didn't realize that errors in my code would get thrown by the shim, but it makes total sense.

**Comment by guybedford** [comment]
If you click on the second line of the stack in this error that was displayed, you will see the real error source. Unfortunately that's the best we can do with this rethrow in Safari unless anyone knows a good way to avoid adding the es-module-shims own stack line here.
