### ISSUE TITLE
Dynamic import that requires external module from import map fails in Firefox, works in Chrome/Edge

### ISSUE THREAD

**Issue by jvissers** [guybedford/es-module-shims#243]
I have a small project that I've been working with trying to get a setup going that uses es-module-shim and dynamic imports. Effectively what I want is for the import map to make available a bunch of core modules, that dynamically imported modules can depend upon. These dynamically imported modules are really tiptap based extensions that need to be loaded from 'somewhere'. This means that the core application, provides a 'shell' if you like for an editor that gets populated with components/configuration (e.g. editor elements like 'paragraph', 'document', 'table') based on some meta-data information.

I am using vitejs as a build environment, and I'm not able to get this to working in 'dev' mode. I have a question about that pending answer on a discord channel. The reason I'm actually now raising this particulare issue is that I'm seeing a problem with the 'build/preview' mode of the project. This manifests itself in the fact that the editor area of a page loads successfully in Chrome/Edge, but not in Firefox. I have tried replacing the dynamic `import(...)` with `importShim(...)`, to no avail.

I'm wondering why this is not working correctly. I can share the GH project here if you want to take a look for yourself.
https://github.com/jvissers/dynamic-import-maps-vite

If you want to verify, follow the following steps after cloning the repo.

```
1. <root> => npm run clean
2. <packages/extension-introduction> => npm run clean
3. <packages/extension-introduction> => npm run build
4. <packages/extension-introduction> => npm run copy
5. <root> => npm run build
6. <root> => npm run copy
7. <remote-extensions> => activate index.html, and start 'LiveServer' on it
   check: http://127.0.0.1:5501/remote-extensions/index.html
8. <root> => npm run preview 
   check: http://localhost:5000/
   
   FF: failures, editor area does not load
   Edge: no failures, editor area loads
   Chrome: no failures, editor area loads
```

**Comment by jvissers** [comment]
For reference, this is what the page looks like when it loads correctly:

![image](https://user-images.githubusercontent.com/2955276/147124873-ceba2593-2ff5-4faf-96e8-7c6d64af2db0.png)

The `Editor area` in Firefox will remain empty.

**Comment by guybedford** [comment]
@jvissers as far as I'm aware, es-module-shims is not compatible with Vite as Vite will attempt to resolve all imports for you.

**Comment by jvissers** [comment]
I was afraid of that yes :-(  as I did the same setup w/o vite - that seemed to work just fine. I was kinda hoping that I could piggy back from vitejs to have support for things like hmr, esbuild, typescript plugins and what not (for dev) - but it seems that indeed there is some problem there. I will reach out to the vitejs team once more to see whether I can get some confirmation. Thanks for the quick response.

**Comment by jvissers** [comment]
Still... what I find strange though is that the production build works fine on Chrome/Edge, whereas it fails for Firefox...
And that is/was basically my real question for es-module-shim (see also the GH project with which you can reproduce this issue).

**Comment by guybedford** [comment]
If you use `importShim` it will work - but note that you will be loading modules twice - a version in the main loader and a separate version for the `importShim` loader.

I managed to get it to work with this diff:

```
diff --git a/index.html b/index.html
index 9f7a306..e8fbd9a 100644
--- a/index.html
+++ b/index.html
@@ -4,8 +4,6 @@
     <meta charset="UTF-8" />
     <link rel="icon" type="image/svg+xml" href="favicon.svg" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
-    <script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>
-    <link rel="stylesheet" href="//unpkg.com/@highlightjs/cdn-assets@11.3.1/styles/default.min.css" />
     <script type="importmap">
       {
         "imports": {
@@ -25,6 +23,8 @@
         }
       }
     </script>
+    <script src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>
+    <link rel="stylesheet" href="//unpkg.com/@highlightjs/cdn-assets@11.3.1/styles/default.min.css" />
     <style>
       #editor {
         border: dashed 1px coral;
diff --git a/package.json b/package.json
index e1eaecb..2b23b41 100644
--- a/package.json
+++ b/package.json
@@ -3,9 +3,9 @@
   "version": "0.0.0",
   "scripts": {
     "dev": "vite",
-    "build": "tsc && vite build",
-    "copy": "copyfiles -V -f ./node_modules/w3c-keyname/index.es.js ./dist/js/w3c-keyname && copyfiles -V -f ./node_modules/orderedmap/index.es.js ./dist/js/orderedmap && copyfiles -V --up 1 ./node_modules/prosemirror*/dist/index.es.js ./dist/js && copyfiles -V --up 1 ./node_modules/@tiptap/*/dist/*.esm.js ./dist/js",
-    "clean": "rimraf ./dist && rimraf ./tsconfig.tsbuildinfo",
+    "build": "tsc ; vite build",
+    "copy": "copyfiles -V -f ./node_modules/w3c-keyname/index.es.js ./dist/js/w3c-keyname ; copyfiles -V -f ./node_modules/orderedmap/index.es.js ./dist/js/orderedmap ; copyfiles -V --up 1 ./node_modules/prosemirror*/dist/index.es.js ./dist/js ; copyfiles -V --up 1 ./node_modules/@tiptap/*/dist/*.esm.js ./dist/js",
+    "clean": "rimraf ./dist ; rimraf ./tsconfig.tsbuildinfo",
     "preview": "vite preview"
   },
   "devDependencies": {
diff --git a/packages/extension-introduction/package.json b/packages/extension-introduction/package.json
index 6631a24..4bdd2cf 100644
--- a/packages/extension-introduction/package.json
+++ b/packages/extension-introduction/package.json
@@ -2,8 +2,8 @@
   "name": "@tangelo/dynamic",
   "version": "1.0.0",
   "scripts": {
-    "build": "tsc && vite build",
-    "clean": "rimraf ./dist && rimraf ./tsconfig.tsbuildinfo",
+    "build": "tsc ; vite build",
+    "clean": "rimraf ./dist ; rimraf ./tsconfig.tsbuildinfo",
     "copy": "copyfiles -V ./dist/extension-introduction.esm.js ../../remote-extensions/extension-introduction"
   },
   "files": [
diff --git a/src/main.ts b/src/main.ts
index 3df5b9f..a6a7b03 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -28,7 +28,7 @@ createApp(App).mount('#vue');
 const editorSlot = document.querySelector<HTMLDivElement>('#editor')!;
 const extensions: AnyExtension[] = [Document, Paragraph, Text];
 let intro = 'remote-extensions/extension-introduction/dist/extension-introduction.esm.js';
-import(`http://127.0.0.1:5501/${intro}`).then((m) => {
+globalThis.importShim(`http://127.0.0.1:5501/${intro}`).then((m) => {
   extensions.push(m.default);
   new Editor({
```

**Comment by jvissers** [comment]
Thank you for taking the time to look into this issue. Indeed I found that this actually works with `importShim` - hence closing as it is not really an issue with es-module-shim.

**Comment by JayaKrishnaNamburu** [comment]
@jvissers one thing i could think of is, can you move the `es-module-shims` to the top of the `import-map`. Because `chromium` based browser engines, `chrome` and `edge` supports import-maps and dynamic import-maps well. But not the same story with `firefox` and `safari`. And that's the reason why the deps resolve when you use `importShim`. If the `es-module-shims` is the first thing that loads in the `index.html` file. Then the `importmap` gets processed using the `shim`
https://github.com/jvissers/dynamic-import-maps-vite/blob/main/index.html#L26

And one more thing, you can try is. Using it in `shimMode`
https://github.com/guybedford/es-module-shims#shim-mode-option

And building the project with `vite` is a issue. As you it's mentioned above `vite` tries to resolve any deps in `dev-mode` for dependency pre-bundling. Even if we define in `exclude` in `esbuildOptions` and `rollupOptions`. So, `vite` in devMode to ignore deps is something i am too waiting for.

Here was my take on that
https://github.com/vitejs/vite/discussions/6246

**Comment by jvissers** [comment]
Thank you @JayaKrishnaNamburu for your input. For my example project (see above) I tried various combinations - and this is what worked in the end (**only for production build**)

In **index.html**
- have _importmap_ first, followed directly by
- es-module-shim.js script tag

In **main.ts** referenced from _index.html_
- use `globalThis.importShim`

**Comment by JayaKrishnaNamburu** [comment]
Yup, exactly the same setup i am using for my workflows.  Need vite aspects for bundling and at the same time power of import-maps. Hopefully sometime soon 🤞

**Comment by jvissers** [comment]
Quite frankly though for what I'm trying to do, the fact that vite dev doesn't support importmaps kinda ruins the experience a bit. I have a setup without vite, simply using `LiveServer` alone that is easier to work with.

```
 "dev": "tsc ; concurrently \"tsc -w\" \"live-server --port=5501\"",
```
