### ISSUE TITLE
importmap seems to work incorrectly in polyfill mode

### ISSUE THREAD

**Issue by thepassle** [guybedford/es-module-shims#244]
Im a little bit confused about the behavior im seeing from es-module-shims, and its making me feel like im holding it all wrong, so I figured I'd make an issue. Bear with me (there's also a [reproduction repro](https://github.com/thepassle/ems-repro) which hopefully makes it easier to grok):

In my projects build, I end up with an `./index.html` that (in order):
- loads a [script](https://github.com/thepassle/ems-repro/blob/master/import-map.js) named `./import-map.js` which dynamically creates an importmap and appends it to the document.head. The contents of this importmap are: `{"imports": {"foo":"./foo.js"}}` (for the sake of reproduction)
- loads `./es-module-shims.js`
- an [inline dynamic script](https://github.com/thepassle/ems-repro/blob/master/index.html#L7-L17) (it creates a script element with type='module' and appends it to the document.head) that loads the `./chunk.js` thats output by rollup, and contains my bundled code. Of note: this script tag gets removed in its `onload` event

`./chunk.js` contains a dynamic import to `./chunk-1.js`, which contains a static import to `import 'foo';`, which I would expect to be resolved via the importmap to `./foo.js`.

`./chunk.js`:
```js
import('./chunk-1.js');
```

`./chunk-1.js`:
```js
import 'foo';
```

According to the documentation, I'm running `es-module-shims` in `polyfill mode`. My expectation is that EMS will polyfill importmaps on browsers that dont support it. What I'm seeing however is (in browsers that dont support importmaps):
```
Uncaught TypeError: Error resolving module specifier “foo”. Relative module specifiers must start with “./”, “../” or “/”.
```

So my first question is: Am I wrong in expecting that this import should work? It'd be my preference to use `type="module"` and `type="importmap"` instead of shimMode if I can avoid it.

After trying to get this to work for some time, I did decide to try `shimMode`. My expectation was that by setting the type of the importmap script to `importmap-shim` and the type of the module for `./chunk.js` to `module-shim`, it should work. This indeed worked correctly, and `import 'foo';` correctly gets resolved to `./foo.js`. However; it seems that changing the script type of the importmap script to `importmap-shim` seems unnecessary, it already started working after changing the type of the module for `./chunk.js` to `module-shim`. 

So my second question is: Is that expected behavior? I would expect, when running in `shimMode`, I would have to use both `importmap-shim` as well as `module-shim`, but using only `module-shim` seems to work.

I've made a reproduction repo [here](https://github.com/thepassle/ems-repro) for the first question here, I've tried to make it as simple as possible, I hope its helpful 🙂

**Comment by guybedford** [comment]
@thepassle the basic rule is that only failed static module graphs will be polyfilled. The reason for this is that if you have a dynamic import that imports something that needs import maps, but the rest of the static graph doesn't then the browser will execute it fine so we would get double execution. To avoid double execution the rule is that only static graphs that fail get reexecuted by the polyfill. The polyfill determines this by graph analysis - this graph analysis could just as easily make this code work, but the problem is double execution which we seek to avoid.

Thus it is always advisable to ensure there is a bare specifier in the static graph so that it will fail fast, then the polyfill will kick in.

This is discussed in more detail here - https://github.com/guybedford/es-module-shims#polyfill-edge-case-dynamic-import.

**Comment by thepassle** [comment]
Thanks for the quick reply @guybedford , im not sure I completely understand correctly. So as I read this is: If you use EMS in polyfill mode, and you have a static graph that fails execution (for example by having a bare specifier in the static graph to make it fail fast, e.g.: `import 'dsafadsfadsf';`), then the polyfill should kick in and re-execute the module? But for dynamic imports this is not the case? Just trying to make sure my understanding of the reasoning is correct 🙂 

In any case, what do you think would be the most idiomatic way forward here? To just use `module-shim` on my script that loads `'./chunk.js'`?

**Comment by guybedford** [comment]
For this specific case, try using `importShim()` instead of the dynamic `import()`. That will then engage the polyfill path at that point only.

**Comment by guybedford** [comment]
(On browsers that support all the features, `importShim` will just then defer to normal dynamic import)

**Comment by thepassle** [comment]
Using `importShim` also seems to fail:
![image](https://user-images.githubusercontent.com/17054057/149316976-340d62d7-1514-45a1-b4ce-ef92b6aa436f.png)

And then that'd mean I'd have to transform any dynamic imports in my rollup build to use importShim I guess? I was hoping to get away without having to do something like that 😅 At this point, is it not just easier for me to use shimMode instead? Do I understand correctly that using shimMode will just immediately use the polyfill for both static and dynamic graphs, as well as respect the importmap?

**Comment by guybedford** [comment]
Ah I see you do have a bare specifier in your `chunk.js` static graph though with "foo"? I'm probably not understanding your use case fully then.

**Comment by thepassle** [comment]
Ugh, sorry, that import shouldnt have been there 🤦 My bad. If I remove that "foo" import, `importShim` indeed does work. 
![image](https://user-images.githubusercontent.com/17054057/149318055-a63ee8d0-9821-4228-931f-e94022ee72d4.png)

My question then still stands though; that would mean I'd have to transform any dynamic import in my app to `importShim`, at which point, would it not be easier for me to just use shimMode directly?

**Comment by guybedford** [comment]
@thepassle the benefit of polyfill mode is getting full native passthrough. The goal then to get that performance benefit is simply to make it as easy as possible for es-module-shims to know if it should polyfill. Map the top-level module with a `<script type="module">import 'toplevel'</script>` to achieve this, that's usually the best bet.

**Comment by thepassle** [comment]
Either I'm really just not understanding, but that seems to just not work. The top level module in this case is `'./chunk.js'`. If I add a `import 'whatever'` in there, it doesnt work (e.g. see the screenshot I posted [here](https://github.com/guybedford/es-module-shims/issues/244#issuecomment-1012023320)). 
![image](https://user-images.githubusercontent.com/17054057/149319680-605daf1b-2479-4fd0-ab6a-a4e2f7e47f6f.png)


If I add a `<script type="module">import 'toplevel'</script>` anywhere else in the `index.html` that also doesnt seem to work.
![image](https://user-images.githubusercontent.com/17054057/149319755-b792575d-7692-44a9-8d39-2dab30fb7dfc.png)


Sorry to bug you about this, I very much appreciate your help 🙏

**Comment by guybedford** [comment]
No problem, it certainly helps to understand how to make the guidance clearer. You'd need an initial import map in the page for it to work natively -

```html
<script type="importmap">{"imports": { "whatever": "./chunk.js" }}</script>
```

**Comment by thepassle** [comment]
No I dont think any action is required, thanks again (a lot!) for the guidance 🙂
