### ISSUE TITLE
CSS Modules is not properly handled with CSS that includes an unquoted URL

### ISSUE THREAD

**Issue by akhmedgaziev** [guybedford/es-module-shims#245]
Example:

source:
`background-image: url(img/product-dark-blue.jpg);`

result:
`background-image: url(undefinedhttps://example.com/static/img/product-dark-blue.jpgundefined);`

**Comment by guybedford** [comment]
Thanks for reporting - fixed in https://github.com/guybedford/es-module-shims/pull/252.
