### ISSUE TITLE
import.meta.resolve polyfill usage detection

### ISSUE THREAD

**Issue by joelmoss** [guybedford/es-module-shims#250]
I'm trying to use the `import.meta.resolve` function, but getting errors.

```html
<script async type="module">
  const res = await import.meta.resolve('./application.js')
</script>
```

...results in `Uncaught TypeError: (intermediate value).resolve is not a function`.

So I try in shim mode:

```html
<script async type="module-shim">
  const res = await import.meta.resolve('./application.js')
</script>
```

which gives me `es-module-shims.js? [sm]:770 TypeError: Cannot read properties of undefined (reading 'replace')`

Apologies if I'm doing something wring here, so any help would be appreciated. thx

**Comment by guybedford** [comment]
The polyfill will run the native loader in passthrough mode when it thinks it can. By default `import.meta.resolve` usage is not currently part of these checks, although we could certainly extend it to support that.

You can work around this for now by either using shim mode, or by using another feature that is checked by the polyfill like import maps at the static dependency level.

I will leave this issue open to track import.meta.resolve detections in the polyfill detection system.

**Comment by joelmoss** [comment]
Yeah, but it also failed in shim mode with

```html
<script async type="module-shim">
  const res = await import.meta.resolve('./application.js')
</script>
```

which gave me the error: `es-module-shims.js? [sm]:770 TypeError: Cannot read properties of undefined (reading 'replace')`

**Comment by guybedford** [comment]
Yes that's a bug - to do with the URL not being defined for the inline script. If you put it in a separate JS file it should work.

**Comment by joelmoss** [comment]
ooh nice! That worked! I could have sworn I already tried that 🤔

Anyway, thx

**Comment by guybedford** [comment]
Fixed in https://github.com/guybedford/es-module-shims/pull/251. I think we will wait on `import.meta.resolve` detection until there is a clearer path forward for the browser spec.
