### ISSUE TITLE
Dynamic import of CSS modules incorrect argument replacement

### ISSUE THREAD

**Issue by joelmoss** [guybedford/es-module-shims#255]
The following code:

```html
<script async src="https://ga.jspm.io/npm:es-module-shims@1.4.4/dist/es-module-shims.js"></script>
<script type="module-shim">
  const path = '/application.css'
  await import(path, { assert: { type: 'css' } })
  await import('/application.css', { assert: { type: 'css' } })
</script>
```

Results in:

```javascript
const path = '/application.css'
await importShim(path, { assert: { type: 'css' } }, 'https://mysite.test/authentication/new')
await importShim('/application.css', 'https://mysite.test/authentication/new', { assert: { type: 'css' } })
```

As you can see, when a variable is used as the first argument to `import()`, the arguments to `importShim()` are incorrect (`path, assertion, parentUrl`), instead of the the correct (`path, parentUrl, assertion`)

**Comment by guybedford** [comment]
It seems like this might have been introduced in https://github.com/guybedford/es-module-shims/pull/248/files.

Seems it's just a simple rewrite ordering issue, thanks for posting.

**Comment by guybedford** [comment]
//cc @ICodeMyOwnLife

**Comment by ICodeMyOwnLife** [comment]
I’ll look into it. Never used dynamic import with dynamic paths before :)

**Comment by ICodeMyOwnLife** [comment]
@guybedford 
With this source code
```js
... import(dynamicJsonPath, { assert: { type: "json" } }).then( ...
```
`lexer` will parse into something like this
```js
{
  a: -1
  d: 794
  e: 846
  n: undefined
  s: 801
  se: 846
  ss: 794
}
```
Note that `e` is equal to `se` and `source.slice(s, e)` is evaluated to be `dynamicJsonPath, { assert: { type: "json" } }`. With just these parameters we can't extract only the first argument. We may need to update `lexer` to give us more information?

**Comment by guybedford** [comment]
@ICodeMyOwnLife it could definitely be useful to track the `,` position in es-module-lexer, but the easier option for now might be to just change the `importShim` function to rather have the signature:

```js
importShim(specifier: string, opts: object, parent?: string)
importShim(specifier: string, parent?: string)
```

where a `typeof arg` for the second argument could branch on being a string, undefined or object. Let me know if that sounds like it can work to you.

**Comment by ICodeMyOwnLife** [comment]
It’s a good idea, I’ll try.
