### ISSUE TITLE
Dynamic CSS Module import fails when polyfilled

### ISSUE THREAD

**Issue by joelmoss** [guybedford/es-module-shims#277]
```html
<script>
  window.esmsInitOptions = { "polyfillEnable": ["css-modules"] }
</script>
<script async src="https://unpkg.com/es-module-shims@1.5.2/dist/es-module-shims.js"></script>
<script async src="https://unpkg.com/construct-style-sheets-polyfill@3.1.0/dist/adoptedStyleSheets.js"></script>
<script type="module">
  const path = '/app/views/layouts/application.css'
  const styles = import(path, { assert: { type: 'css' }})
  console.log({styles});
</script>
```

In chrome, this works fine (because its not polyfilled I believe).

But in Safari, this fails with `SyntaxError: Unexpected token ','. import call expects exactly one argument.`. Which I know is expected, however, that error is printed twice, and therefore the `console.log()` call is not executed.

It looks like the dynamic import is not actually polyfilled, as the produced code is unchanged from the source.

**Comment by guybedford** [comment]
@joelmoss the way that es-module-shims works in polyfill mode is that it will only polyfill **static failures**. The dynamic import with assertions is a dynamic failure, so the polyfill won't work in this case.

Instead of using `import()` try using `importShim()` instead:

```html
<script type="module">
const path = '/app/views/layouts/application.css';
importShim(path, { assert: { type: 'css' } });
</script>
```

Alternatively, make the CSS import a static feature like:

```html
<script type="module">
import '/application.css' assert { type: 'css' };
</script>
```

**Comment by joelmoss** [comment]
Ok but if I use importShim, won't that bypass native import for browsers that support them?

**Comment by guybedford** [comment]
No, passthrough will still apply with `importShim` when browsers support the static features being imported.

**Comment by joelmoss** [comment]
I don't really want to change all my code to use `importShim`, so am I right in saying that I would have to run everything in shim mode?

And is passthrough still applied in shim mode?

**Comment by guybedford** [comment]
@joelmoss you only need to use `importShim` to enter the polyfill mode, after that you don't need it. The important thing is to ensure the polyfill is triggering at the top-level of the application code run, by either ensuring the code will statically error in unsupported browsers, or uses `importShim` on the dynamically coded code that in turn will static error.

**Comment by joelmoss** [comment]
Sorry, but now I'm a little confused...

If I want to use a dynamic import, I have to use `importShim()`, but only for the first dynamic import call? Would setting the `shimMode: true` option not be simpler and achieve the same thing?

**Comment by guybedford** [comment]
> If I want to use a dynamic import, I have to use importShim(), but only for the first dynamic import call?

That is correct.

The basic principle is one of avoiding double execution. The polyfill will only kick in when the native execution fails. A dynamic import doesn't count as a failure because the module containing the dynamic import still executed. You can read about this more at https://github.com/guybedford/es-module-shims#polyfill-edge-case-dynamic-import.

**Comment by joelmoss** [comment]
Would setting the `shimMode: true` option not be simpler and achieve the same thing?

**Comment by guybedford** [comment]
@joelmoss that is your decision to make.

**Comment by joelmoss** [comment]
Sorry, I think you misunderstand me. Is calling `importShim` the same as running in `shimMode`?

**Comment by guybedford** [comment]
See https://github.com/guybedford/es-module-shims#shim-mode. I'm closing this as resolved, but feel free to continue to discussion.

**Comment by jorgecasar** [comment]
I'm using web test runner mocha that dynamically import the test file, then import assertions inside this test file doesn't work.

Does the solution pass throw replace import by importShim in the library?

https://github.com/modernweb-dev/web/blob/master/packages/test-runner-mocha/src/autorun.ts#L23

something like this `await (importShim ?? import)(new URL(testFile, baseURI).href)`?

**Comment by guybedford** [comment]
@jorgecasar load ordering is highly dependent on the original dom load of the page, so dynamic loading of tests will change that. If you want to share more info on what you're looking to achieve I can try to come up with some better suggestions.
