### ISSUE TITLE
Need to migrate to using navigator.userAgentData

### ISSUE THREAD

**Issue by joehonton** [guybedford/es-module-shims#278]
Chrome inspector issues this audit message with Chrome version 99.0.4844.84:

- A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.

 - To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.

**Comment by guybedford** [comment]
Thanks, I've added a fix in https://github.com/guybedford/es-module-shims/pull/279.
