### ISSUE TITLE
Feature detection polyfill strategy

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-shims#29]
Chrome has import maps enabled behind a flag, and will start shipping it at some point. So will other browsers.

This means that soon there will be browsers for which the shim doesn't add any new functionality (until you implement top level await, but then it's also a matter of time).

Do you intend for `es-module-shims` to do feature detection to decide whether it should do any work, or do you expect the anyone who uses the shim to not load the shim unless needed?

**Comment by guybedford** [comment]
See https://github.com/guybedford/es-module-shims/issues/16 for some related discussion here.

Yes, the goal of this project is to become a polyfill. Now that the Chrome implementation is becoming more stable, I'm open to handling those feature detections definitely.

For example implementing builtin modules, or only shimming worker imports when needed.

The risk though is that implementing polyfills before a spec is stable can lead to fragmentation so we need to balance that.

Perhaps a special experimental flag to switch into a "polyfill mode" initially where we remove the `shim` prefixing (or possibly even separate script).

**Comment by LarsDenBakker** [comment]
I think a separate tag which evolves as the spec evolves would be great, but indeed let's first see import maps settle a bit more.

**Comment by guybedford** [comment]
Let's reopen this when import maps DO become unflagged in browsers. The support matrix requirements stem from there I think.
