### ISSUE TITLE
Relative file path mappings.

### ISSUE THREAD

**Issue by MicahZoltu** [guybedford/es-module-shims#3]
A comment over on the proposal issues (https://github.com/domenic/import-maps/issues/89#issuecomment-452344475) suggests that I should be able to map `import './apple'` with something like:
```json
{ "packages": { "/apple": "/apple.js" } }
```
However, I am unable to get this working with this tool.  Am I misunderstanding the spec/comment, or is it a bug in this tool?

**Comment by guybedford** [comment]
This project is still using the previous version of the specification at https://github.com/domenic/import-maps/tree/4f449c03a3d007734b633380b84e356aed2b4bb6.

I'm hoping to update to the new spec very soon though.

**Comment by guybedford** [comment]
That said I'm still against the URL mapping feature as I believe it conflates the meaning of URL resolution and that the polyfill and stdlib mapping problems can be solved without losing this invariant.

**Comment by MicahZoltu** [comment]
Does that mean the current implementation doesn't support mapping of relative paths at all?  So in the example, I can't map `./apple` to something else?

Also, do you have any idea what the timeline is on updating to the new spec?

**Comment by guybedford** [comment]
Yes exactly, because it is treated as a URL-like resolution over a bare specifier resolution. The current spec makes this distinction hazy again though.

I'm aiming to put some time aside in the next week.
