### ISSUE TITLE
Release 1.5.7 does not initialize in safari 15.6 🥲

### ISSUE THREAD

**Issue by PonomareVlad** [guybedford/es-module-shims#303]
![Снимок экрана 2022-06-20 в 08 25 28](https://user-images.githubusercontent.com/2877584/174520520-95fd981b-a9b0-426a-81d2-c0e38c772ecd.png)

![Снимок экрана 2022-06-20 в 08 26 28](https://user-images.githubusercontent.com/2877584/174520526-d7528240-eca2-48ef-b1a0-dbbe0eebbfe7.png)

**Comment by guybedford** [comment]
Fixed in 1.5.8.
