### ISSUE TITLE
Polyfill is not kicking in when required

### ISSUE THREAD

**Issue by zachsa** [guybedford/es-module-shims#315]
Hi Guy,

This shim is not kicking in on https://somisana.ac.za/visualizations

In Chrome:

1. Load the site without any extensions (should work)
2. Install Apollo tools extension, and load the site (it doesn't work)

Below is a screenshot of the error in the console (the minified React error is present in both cases and relates to the renderToString method serverside - I think it can be ignored in this case)

![image](https://user-images.githubusercontent.com/6336500/182585290-36192c3e-c117-47a1-b92e-6beedaffac9d.png)

**Comment by guybedford** [comment]
When I navigate to the page above in a browser _with_ import maps support, I'm still seeing an error - `Uncaught TypeError: Failed to resolve module specifier "react/jsx-runtime". Relative references must start with either "/", "./", or "../".`. Are you sure the import map is correct in the first place?

The parse error is interesting, and may well be a bug in es-module-lexer. I tried looking into those two modules from the error: https://ga.jspm.io/npm:@arcgis/core@@4.23.7/_2be1ce80.js and https://ga.jspm.io/npm:@arcgis/core@@4.23.7/_bc30bbeb.js, but both seem to be not found. Is that the issue?

**Comment by guybedford** [comment]
This has been resolved in https://github.com/guybedford/es-module-shims/pull/317 and https://github.com/guybedford/es-module-shims/pull/318. Thanks for sharing the case.
