### ISSUE TITLE
Bug: 1.5.11 has been published to NPM but appears to be broken

### ISSUE THREAD

**Issue by cannontrodder** [guybedford/es-module-shims#319]
Hi, one of our apps was pulling in this package using the 'latest' tag and we've just reverted to 1.5.10 as it broke things.

It seems that the github action tests are failing for this merge but this is published to npm.

**Comment by guybedford** [comment]
@cannontrodder please post the exact issue you're getting. If you look at the CI failure it's not an actual failure but a flake. I cannot fix a problem I can't replicate.

**Comment by guybedford** [comment]
I was able to work out a replication in the end. Fix posted in https://github.com/guybedford/es-module-shims/pull/320.

**Comment by cannontrodder** [comment]
Thanks @guybedford - sorry I did not come back sooner
