### ISSUE TITLE
1.5.14: Cannot read property 'head' of null

### ISSUE THREAD

**Issue by andys8** [guybedford/es-module-shims#324]
When I test multiple versions, only 1.5.12 seems to function for me across all of the browsers I use. The most noteworthy part is that the most recent release 1.5.14 also has a bug, despite the fact that I checked more versions (which are detailed [here](https://github.com/purescript/trypurescript/pull/297#issuecomment-1214187241)).

It may be important to point out that the importmap is used within an iframe. Perhaps that is relevant given the error message.

Are you able to identify the likely cause and replicate the problem using the information provided?

> es-module-shims.js? [sm]:342 Uncaught TypeError: Cannot read property 'head' of null
    at HTMLIFrameElement.n.onload

![image](https://user-images.githubusercontent.com/13085980/184504882-88db2ed3-30eb-4380-93b9-4c636743436b.png)

![image](https://user-images.githubusercontent.com/13085980/184504876-c221846b-857c-4761-acff-3842709a2943.png)

**Comment by guybedford** [comment]
@andys8 thanks for reporting! Can you try updating the HTML of the import map test to rather start with:

```js
const importMapTest = `<html><script type=importmap nonce="...`
```

and let me know if that resolves the issue for you?

**Comment by guybedford** [comment]
Of course explicitly adding `<head>` I mean, corrected above.

**Comment by andys8** [comment]
The code where the error is coming from is from `es-module-shins`.

https://github.com/guybedford/es-module-shims/blob/d01d99a4d418824d2bbac45f98d1fc33ae08ae7a/src/features.js#L49

Do I understand correctly that you want me to change it - e.g. fork the dependency or manipulate it somehow in the browser debugger - to verify it would change the behavior and potentially solve the issue?

**Comment by guybedford** [comment]
@andys8 yes if you just use a local version of es-module-shims with the change described. Would help if you can test it since I don't have a clear replication this side.

**Comment by andys8** [comment]
Hmm, it doesn't look like it would solve the problem (I tried it).

* `importMapTest` is defined in the line **after** the error happens. It shouldn't have any impact. Anyway, I also changed `srcdoc` some lines above and it didn't change the behavior.
* It is not `.head` that is `null`, it's `contentDocument` that is already `null`.

I'll try to come up with a reproducer for the issue. That would make debugging way easier.

**Comment by guybedford** [comment]
Yeah, it would help to see how you are injecting es-module-shims that there's no head available.

**Comment by andys8** [comment]
Again, I think it's not about `head`. Any field on `null` will fail.

> Cannot read property 'head' of null

**Comment by guybedford** [comment]
I see what you mean. Which browser are you using here?

**Comment by guybedford** [comment]
This codedpath is specifically trying to detect `srcdoc` support for Iframes. If the browser doesn't support srcdoc then we could add an extra conditional when `iframe.contentDocument` is `null` to indicate that `supportsSrcDoc = false`.

But if this browser _does_ support srcdoc setting for iframes, then we should fix the feature detection for srcdoc to find the right event handler to attach to that will ensure `iframe.contentDocument` or `iframe.contentWindow` is defined for us to check if the feature detection passed.

**Comment by andys8** [comment]
Could you try if https://github.com/andys8/es-module-shims-issue-324 is a potential reproducer for the issue?

A bunch of other code is still in there which will lead to other irrelevant errors, but it does produce the issue we're looking for when I test with Chrome/Chromium 87 or Firefox 103.

**Comment by guybedford** [comment]
Tried in Firefox, but that doesn't seem to replicate it for me - 

![image](https://user-images.githubusercontent.com/598730/184548074-cc687bcf-f4ef-4a61-92a1-877a17b08792.png)

**Comment by andys8** [comment]
I [pushed another change](https://github.com/andys8/es-module-shims-issue-324/commit/a7184ad68f54d54fe5cd2f727bd5b6e549a548e5) to minify the example further.

![image](https://user-images.githubusercontent.com/13085980/184548135-fa2afd30-e49e-4836-b855-63c1da1e9f2d.png)

Can you try again? I'm not sure if the CORS error that you saw happens earlier than the issue. And which version of Firefox did you try it with?

**Comment by andys8** [comment]
Hosted version: https://andys8.github.io/es-module-shims-issue-324/

**Comment by guybedford** [comment]
Got it thanks, I think I can find a fix.

**Comment by andys8** [comment]
Nice, I could also reproduce it in browserstack (Firefox 102).

![image](https://user-images.githubusercontent.com/13085980/184548433-3555a13c-8e48-4a81-af4b-5f1b833805c9.png)

**Comment by guybedford** [comment]
Thanks for creating the reproduction, I've incorporated it as a test now into the fix at https://github.com/guybedford/es-module-shims/pull/325.

**Comment by guybedford** [comment]
Fix released in 1.5.15.

**Comment by andys8** [comment]
I think the issue described in this ticket is solved. Updating the reproducer will not show the error anymore.

However, although this is offtopic for this issue, there has to be another issue that was introduced in 1.5.13. It did not exist in 1.5.12 and exists in all versions including 1.5.15.

Here is a demo of the project I'm contributing to comparing several versions, although it's probably not helpful enough for debugging.


https://user-images.githubusercontent.com/13085980/184555629-d7d5cace-471c-4693-bf57-30b1d54c8333.mp4

**Comment by guybedford** [comment]
Unfortunately without further logs / debugs around what about the bootstrap is different it's not really possible to advise. That you are getting the console message shows that the polylfill is kicking in fine. It may be something to do with ready events / dom attachment then? I'd advise logging your DOM attachment initialization code carefully to see where the flow is breaking.

**Comment by guybedford** [comment]
@andys8 I just released a 1.5.16 that resolved what looked like a similar issue on one of my apps here. Perhaps try out this version and see if that solves the next issue for you.

**Comment by andys8** [comment]
Thanks for the hint. Tried it and documented the result in this comment https://github.com/purescript/trypurescript/pull/297#issuecomment-1215922411

I do think the tricky part is that this project is [adding an event listener that can add a script](https://github.com/purescript/trypurescript/blob/3cdcc8ff97a9089efc522dfed7d55637f3c3ce97/client/public/js/frame.js#L4-L14).

**Comment by guybedford** [comment]
@andys8 that makes sense. I've added a final PR in https://github.com/guybedford/es-module-shims/pull/328 that may well resolve the issue as well. Perhaps you can apply the one line patch locally to test?

**Comment by andys8** [comment]
#328 seems behave the same way that 1.5.16 does.

**Comment by guybedford** [comment]
Thanks for the update. Is that injected script executing in these cases or not? That is - is the problem entirely timing, or also execution? I've done about as much as I can without another replication this side - do share any specific cases further if you can.

**Comment by andys8** [comment]
I wish I could give more information or a reproducer, but it's a project I'm just contributing to. I think it has to do with the way it's setup using iframes, Postmessage, eventlisteners and dynamically executing code. All I see is that versions after 1.5.12 behave differently regarding eventlisteners setup with `once: true`. If I can boil it down to a simple reproducer or have more information, I'll create an issue and let you know. Thanks for your efforts!
