### ISSUE TITLE
Are esmInitOptions supported?

### ISSUE THREAD

**Issue by ilteoood** [guybedford/es-module-shims#332]
Hi,
first of all: thank you so much for this amazing shim: I'm trying to use it to ship my new project.

I'm reading [here](https://github.com/guybedford/es-module-shims#init-options) about `esmInitOptions`, but they does not seems to work anymore. The same configuration, inserted in the script type `esms-options` works perfectly.

Lookin' at the code [here](https://github.com/guybedford/es-module-shims/blob/main/src/env.js#L8), I see that you only search for the script: is the configuration on the window really supported?

Otherwise, I think that the readme should be updated accordingly.

**Comment by ilteoood** [comment]
Hi, I investigated more: the configuration is correctly loaded in both ways, only if you place them above the import of `es-module-shims`.

Currently, I'm including this in a web component as module, so I can init the configuration only **after** `es-module-shims` has been imported.

An example of my current (wrong) usage is:

```
...other imports...
import 'es-module-shims'

window.esmsInitOptions = {"shimMode": true}

...web component definition...
```

As workaround, I've found this:

```
...other imports...
import './esmsInitOptions'
import 'es-module-shims'

...web component definition...

where, `esmsInitOptions` contains only:
```
window.esmsInitOptions = {"shimMode": true}
```

Is this the correct procedure? Do you suggest something else?

Thank you so much,
Matteo

**Comment by guybedford** [comment]
The initialization options apply immediately when es module shims is loaded. Whatever way you find works to do that is fine.

**Comment by ilteoood** [comment]
Thank you for your help
