### ISSUE TITLE
Setting esmsInitOptions in .js

### ISSUE THREAD

**Issue by tve** [guybedford/es-module-shims#345]
I'm facing challenges enforcing loading order when I can't modify the top-level .html file, e.g., when loaded into an existing page. Specifically, without html file, e.g. in a top-level main.js, how do I enforce that the esmsInitOptions are set, then es-module-shims loads and inits, and then the rest of the app loads (that depends on the importmap being there)?

For example, this doesn't work due to hoisting and async of import statements:
```
window.esmsInitOptions = {
  shimMode: true
}
import "es-module-sims"
import "rest-of-app.js"
```

Is something like this guaranteed to work?
```
window.esmsInitOptions = {
  shimMode: true
}
import("es-module-sims").then(m => {
  import("rest-of-app.js").then(app => { /* call some export, if needed */ })
})  
```
I'm probably missing some obvious trick...

**Comment by chase-moskal** [comment]
@tve 
> I can't modify the top-level .html file

hopefully you can still interact with the dom -- then you could write a `load` function which can create a script element and append it to the document head:

```js
function load(type, src) {
  const script = document.createElement("script")
  script.type = type
  script.src = src
  script.defer = true
  script.onload = resolve
  script.onerror = reject
}
```

then you can proceed to attach the importmap-shim and the module-shim -- then, once you load es-module-shims, it will do its magic, and load and finally execute those `-shim` scripts:

```js
load("importmap-shim", "/importmap.json")
load("module-shim", "/main.js")
load("module", "/node_modules/es-module-shims/dist/es- module-shims.wasm.js")
```

if you're "allowed" to interact with the dom in that way, then i'm quite sure that kind of solution will work. there may be a preferable solution worth finding, which i might not be aware of.

best of luck! do ping me if you find a different solution :+1:

**Comment by guybedford** [comment]
Another option here would be:

```js
import './es-module-shims-options.js';
import 'es-module-shims'
```

since modules are always guaranteed to execute in dependency order.
