### ISSUE TITLE
"load" event of a script tag with type "module-shim" is not fired

### ISSUE THREAD

**Issue by paulcodiny** [guybedford/es-module-shims#346]
### Context
I'm trying to integrate a @web/polyfill-loader library into our project. It rewrites the "script[type=module]" in our bootstrap index.html file into "script[type=module-shim]" and adds es-module-shims polyfill. 
The execution of the modules is [ordered](https://stackoverflow.com/a/69064038) by their occurrence, so the polyfill-loader constructs the following code (simplified)
```javascript
const loadScript = (src, type) => new Promise(resolve => {
  const scriptTag = document.createElement('script');
  scriptTag.onload = resolve;
  if (type) scriptTag.type = type;
  scriptTag.src = src;
  document.body.appendChild(scriptTag);
} );

loadScript('es-module-shims')
  .then(() => loadScript('a.js', 'module-shim')
  .then(() => loadScript('b.js', 'module-shim')
```

The key part is that it loads the "es-module-shims" as a "normal" script, then loads whatever we have in the project as "module-shim" scripts.

After some debugging and experimenting with why some scripts are not loaded, I discovered that "onload" handler from "loadScript" is not triggered. In the documentation of es-module-shims I can see that the "load" event [should be triggered](https://github.com/guybedford/es-module-shims#shim-mode-option) (last paragraph) so I'm not sure I'm doing everything correctly.

### Demo

Here is a **demo** of this behavior https://codesandbox.io/s/new-platform-dzyspv. You can see the code above in index.html and in the console the list of loaded modules

### Proposed solution

If I change the code from here
https://github.com/guybedford/es-module-shims/blob/main/src/es-module-shims.js#L548
to
```javascript
const loadPromise = topLevelLoad(script.src || pageBaseUrl, getFetchOpts(script), !script.src && script.innerHTML, !shimMode, isBlockingReadyScript && lastStaticLoadPromise)
  .then(() => {
    if (shimMode) 
      script.dispatchEvent(new Event('load'));
  })
  .catch(throwError);
```

then it works as expected, but I'm not sure this is a correct fix and won't cause any other issues.

Can you suggest the following steps? Make a PR with the proposed change or wait for further examination or something else?

**Comment by guybedford** [comment]
@paulcodiny interesting, yes the load event dispatch code no longer seems to be there! At first glance the change you're suggesting seems ok to me, would be happy to take a PR.

**Comment by paulcodiny** [comment]
Here it goes https://github.com/guybedford/es-module-shims/pull/348
