### ISSUE TITLE
Expose lexer

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-shims#35]
Until import maps are more mainstream, I'd like to use the lexer serverside in https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server to resolve imports before serving them to the browsers.

Is it possible to expose the lexer module so that it can be imported separately?

**Comment by guybedford** [comment]
Maybe it's time to actually make the lexer its own package actually. It is useful outside of this project.

Would you like to set that up here? I don't mind where it lives.

**Comment by LarsDenBakker** [comment]
Yeah I can do that, but where should the package live?

**Comment by guybedford** [comment]
We could create a new shared org for it, or put it under an existing one
like ES Module Loader is SystemJS.

**Comment by LarsDenBakker** [comment]
Seems like https://github.com/ModuleLoader is a good place for this

**Comment by daKmoR** [comment]
just an idea...
new group `es-module-tools` and have a monorepo in there as `es-module-tools`...
at open-wc we have quite some stuff now which is actually not really web components related but more es module related... so we could consider moving some of them 👍 

PS: `es-tools` is sadly already taken

**Comment by guybedford** [comment]
I went ahead and separated the lexer out into its own project at https://github.com/guybedford/es-module-lexer.

Work to ensure this project properly depends on that is still pending. A PR is welcome, otherwise I'll get to it when I'm next working on this project.

**Comment by LarsDenBakker** [comment]
Thanks, I will close this one. If I have time on the weekend I can make a PR.
