### ISSUE TITLE
Slow when using shim to load npm modules

### ISSUE THREAD

**Issue by jogibear9988** [guybedford/es-module-shims#353]
I use your module shim, to allow adding npm packages to my designer via downloading all the dependencies and adding them to importmaps.

But if I do so, the loading after via the importmaps takes very long. Is there anything I can do to speed up?

See: https://node-projects.github.io/web-component-designer-demo/index.html 
add the "@patternfly/pfe-clipboard@next" npm on the right side.

It takes a while to load. When it's ready, drag it to the designer, then the module is loaded via importmaps, but it takes very long (on the first time)

**Comment by guybedford** [comment]
Nice! As far as I can tell most of the slowdown seems to be network related? unpkg is generally not the fastest CDN. Have you tried using jspm.io?

**Comment by jogibear9988** [comment]
no, never heard of. i'll give it a try

**Comment by jogibear9988** [comment]
@guybedford I now tried to switch to: cdn.jsdelivr.net/npm I could not get the package data from jspm.io 
Seems to be faster

**Comment by guybedford** [comment]
Nice, yes jspm only works with the jspm generator project (
https://github.com/jspm/generator) to create the import maps. It also works
well against jsdelivr for map generation.
