### ISSUE TITLE
Relative import inside of module, resolve to wrong path.

### ISSUE THREAD

**Issue by jogibear9988** [guybedford/es-module-shims#355]
I do this inside of a js module  

      cssProperties = await importShim("./CssProperties.json", { assert: { type: 'json' } });

it resolves to the wrong URL. But If I do like this:

    const cssPropertiesUrl = import.meta.resolve('./CssProperties.json')
    cssProperties = await importShim(cssPropertiesUrl, { assert: { type: 'json' } });

it works.
shouldn't this be the default case for paths starting with './' ?

**Comment by guybedford** [comment]
Can you please share a replication of the issue here?

**Comment by guybedford** [comment]
Oh wait, you should be using `await import('./CssProperties.json', { assert: { type: 'json' } })`.

`importShim` is a global and doesn't have contextual resolution like `import` and `import.meta.resolve`.

**Comment by jogibear9988** [comment]
i did use await... I'll create an repro
I is wrong in my designer without the fix, but at the momen chrome is looking for a bug there so I can not push any changes. I'll come back

**Comment by guybedford** [comment]
you must use `import`, not `importShim`.

**Comment by jogibear9988** [comment]
but you don't overwrite import. I have to use importShim, firefox does not yet support assert for css. 
But you mean, for shim it is not fixable?

**Comment by guybedford** [comment]
`import()` is polyfilled in all modules by es module shims.

**Comment by guybedford** [comment]
It might even be advisable in this scenario to use a `module-shim` tag:

```html
<script type="module-shim">
    await import('./some/path.js');
</script>
```

The above ensures that the shim processes the script, while still using the native loader if possible.
