### ISSUE TITLE
Not properly recognized on Firefox 109

### ISSUE THREAD

**Issue by morgoth** [guybedford/es-module-shims#356]
I'm using the ES module shim by the https://github.com/rails/importmap-rails (which I believe uses this code).

On the Firefox 109, looks like the feature is not properly detected as it's supported natively in this version.
My code:
```js
document.addEventListener('DOMContentLoaded', () => {
  console.log("I run")
})
```
is run twice when loading the shim script.

Please see the details on https://github.com/rails/importmap-rails/issues/175

**Comment by guybedford** [comment]
Which version of es-module-shims are you using? Make sure you are using the latest version 1.5.18 here. The detection is definitely correct, and I couldn't get a double execution in my own test case. Otherwise please share an exact replication for further investigation.

**Comment by guybedford** [comment]
Ah apologies, I'm on slow wifi and had an older version on this machine. Posted a fix in https://github.com/guybedford/es-module-shims/pull/358.
