### ISSUE TITLE
Firefox 110 error - 'The specifier “process” was a bare specifier, but was not remapped to anything'

### ISSUE THREAD

**Issue by zachsa** [guybedford/es-module-shims#357]
Going to this URL - https://somisana.ac.za/forecast?id=1, I get an error in Firefox (110.0):

>Uncaught TypeError: The specifier “process” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.

Please let me know if I should debug this more to see where it's coming from or if it's obvious from the console error. This doesn't occur in Chrome/Edge

**Comment by guybedford** [comment]
Thanks for posting. I'm unable to replicate this in the same 110.0 Firefox version. Here's what I see:

![Uploading image.png…]()

**Comment by zachsa** [comment]
Right - I see. thank you for the response, it was a caching issue.
