### ISSUE TITLE
Setting options with "esms-options"

### ISSUE THREAD

**Issue by tomgreenhill** [guybedford/es-module-shims#367]
Hey, 

I've been implementing import maps after having a problem with imports on Shopify and t heir cachebusting/versioning system. Anyway, huge thanks for putting out this shim. 

The one issue I've run in to so far as setting options, I copied the example to ignore Skypack imports but the JSON parsing fails due to new lines within the script block. I've removed them but am still getting illegal character warnings. Could any one please shed some light on this?

<img width="550" alt="Screenshot 2023-03-28 at 12 25 39" src="https://user-images.githubusercontent.com/1922302/228222196-1c4fcd96-36dc-4444-bf09-2280c5dfaef3.png">
<img width="869" alt="Screenshot 2023-03-28 at 12 26 01" src="https://user-images.githubusercontent.com/1922302/228222198-51bf718b-491a-49ec-ba14-ea0b68fe5435.png">

Thanks in advance.

**Comment by guybedford** [comment]
If you want to debug this you can try `document.querySelector('script[type=esms-options]').innerHTML`, and even manually passing that to `JSON.parse` to see how the HTML parser is handling the string that way. Do report what you find!

**Comment by guybedford** [comment]
@tomgreenhill running that string through JSON.parse, the issue is at character 31 which is the `cdn\\.` backslash. Changing it to `cdn\\\\.` seems to help.

**Comment by tomgreenhill** [comment]
So sorry to have wasted your time! Thanks for checking that and responding. I should've caught that, thanks again!
