### ISSUE TITLE
Have some few question.

### ISSUE THREAD

**Issue by jimmywarting** [guybedford/es-module-shims#373]
Hi 👋 

I have used [Shimport](https://github.com/rich-harris/shimport) so far and it have been fantastic so far.
Could you with a few bull-list describe what es-module-shims dose better/differently? is it faster/slower then Shimport?

I also see that you have a WASM version as well. currently it's inlined with base64.
i wish to use `WebAssembly.instantiateStreaming` instead. so that it loads raw bytes instead. but didn't find any such "dist" option.

I wanna try using this inside of service worker that dose not support import maps
nor dose it support lazy loading dynamically imported modules that isn't stored in 
due to this stupid message i get when trying to use dynamic import:
> Uncaught (in promise) TypeError: import() is disallowed on ServiceWorkerGlobalScope
by the HTML specification. See [w3c/ServiceWorker#1356](https://togithub.com/w3c/ServiceWorker/issues/1356).

there is also this one: [w3c/ServiceWorker#1585](https://togithub.com/w3c/ServiceWorker/issues/1585) to cut the story short. only static import statment is supported as of right now 👎 

so that's why i have been using shimport upon till now.

Service worker dose not also support creating Blob URLs. the only valid option is to use eval or constructing a Function with the code. 

So Would this `es-module-shims` work for me inside of service worker to bypass this annoying restriction?

**Comment by jimmywarting** [comment]
i tried a simple service worker but i didn't get far until i stumble upon my first issue

```js
// listen to post messages from the client inside of service worker
importScripts('https://unpkg.com/es-module-shims@1.7.2/dist/es-module-shims.debug.js')

globalThis.esmsInitOptions = {
  // Enable Shim Mode
  shimMode: true, // default false
  // Enable newer modules features
  // polyfillEnable: ['css-modules', 'json-modules'], // default empty
  // Custom CSP nonce
  // nonce: 'n0nce', // default is automatic detection
  // Don't retrigger load events on module scripts
  noLoadEventRetriggers: true, // default false
  // Skip source analysis of certain URLs for full native passthrough
  // skip: /^https:\/\/cdn\.com/, // defaults to null
  // Clean up blob URLs after execution
  revokeBlobURLs: false, // default false
  // Secure mode to not support loading modules without integrity
  // (integrity is always verified even when disabled though)
  // enforceIntegrity: false, // default false
  // Permit overrides to import maps
  // mapOverrides: true, // default false

  // -- Hooks --
  // Module load error
  // onerror: (e) => { /*...*/ }, // default noop
  // // Called when polyfill mode first engages
  // onpolyfill: () => {}, // default logs to the console
  // // Hook all module resolutions
  // resolve: (id, parentUrl, resolve) => resolve(id, parentUrl), // default is spec resolution
  // // Hook source fetch function
  fetch: (url, options) => {
    console.log('fetching', url)
    return fetch(url, options)
  }
  // // Hook import.meta construction
  // meta: (meta, url) => void // default is noop
  // // Hook top-level imports
  // onimport: (url, options, parentUrl) => void // default is noop
}


self.addEventListener('message', function(e) {
  console.log('message received in service worker', e.data)

  // respond to post message with today's date
  e.source?.postMessage(new Date())

  importShim('/clientmyadmin/shared/zip64/read.js').then(async mod => {
    console.log(mod)
  })

})
```
es-module-shims.debug.js:53 Uncaught (in promise) TypeError: URL.createObjectURL is not a function
    at createBlob (es-module-shims.debug.js:53:64)
    at resolveDeps (es-module-shims.debug.js:681:25)
    at topLevelLoad (es-module-shims.debug.js:547:5)
```

like i mention earlier `URL.createObjectURL` don't work inside service worker.

**Comment by jimmywarting** [comment]
fyi, i think you should be using `globalThis` instead of `self`. it's a better alternative then using self, window, this or global

**Comment by guybedford** [comment]
Service workers are not supported for exactly the reasons you mention with dynamic import. That's the only way that es-module-shims works because it needs to dynamically import real modules. That's also it's difference from shim port and why it is so fast - because it uses the native loader directly with a basic wasm rewriting.

We could add a note to the readme about service worker support to help clarify this.

**Comment by jimmywarting** [comment]
Would it not be possible to compile the source into one single javascript bundle and then eval the hole thing?
that is what shimport was able to do.

shimport did something like this:
```js
function evaluate (code) {
  return (0, eval)(code)
}

async function shimport (url) {
  return promises[url] ??= fetch(url)
    .then(r => r.text())
    .then(text => evaluate(transform(text, url)) )
}

const module = await shimport('https://example.com/main.js')
```
(it's a slightly modification/fork of mine)

isn't that something you would be able to accomplish as well with this module?
I would be sad if this would not work inside of service worker.

**Comment by guybedford** [comment]
Yes, shimport handles ESM conversion into non-ESM JS. es-module-shims doesn't do that. es-module-shims uses native ESM to support new ESM features, which is why it's a production suitable polyfill as the rewriting is very minimal.

**Comment by jimmywarting** [comment]
Understood. but quite honestly. i don't see any special need for es-module-shims outside of service worker as they already working fine without it... just slam in `<script type="module" src="">` and it works just fine in all evergreen browser nowdays...

Guess `es-module-shims` isn't anything for me then unless you are willing to create a new issue/feature where you do the same thing as shimimport and transpile the code into non-ESM JS

- [ ] Create non-ESM code like shimimport

anyway gona close this as i got my answer.
really wished shimimport had the same feature you had with Hooks and importmaps
unfortunately there is no middle ground to solve both cases 😞
