### ISSUE TITLE
support also "with" keywork instead of "assert" for import attributes

### ISSUE THREAD

**Issue by jogibear9988** [guybedford/es-module-shims#375]
as the proposal switched from assert to with, see:
https://github.com/tc39/proposal-import-attributes

**Comment by jogibear9988** [comment]
But also keep the assert keyword

**Comment by guybedford** [comment]
This should be already supported in 1.7.3. If there's a case that's not working please do share the scenario.

**Comment by jogibear9988** [comment]
does work
