### ISSUE TITLE
Using hash routing + importmap, The module is resolved to the wrong URL.

### ISSUE THREAD

**Issue by He110te4m** [guybedford/es-module-shims#376]
es-module-shims version: `1.7.3`

My importmap is like this: 

```json
{
  "imports": {
    "vue": "./vue-2_6_14-dev.js",
    "vue-router": "./vue_router-3_6_5-dev.js",
    "@vue/composition-api": "./_vue_composition_api-1_7_1-dev.js",
    "vue-class-component": "./vue_class_component-7_1_0-dev.js",
    "vue-property-decorator": "./vue_property_decorator-9_1_2-dev.js",
    "pinia": "./pinia-2_0_35-dev.js"
  },
  "scopes": {}
}
```

My option is like this:

```js
    window.esmsInitOptions = {
      shimMode: true,
      resolve: (id, parentUrl, resolve) => {
        if (id.startsWith('/')) {
          return resolve(id, parentUrl)
        }

        const baseUrl = id.startsWith('/') ? parentUrl : `${location.protocol}//${location.host}`
        const resolvedID = resolve(id, baseUrl)
        console.warn(
          `id: ${id}`,
          `parentUrl: ${parentUrl}`,
          `baseUrl: ${baseUrl}`,
          `resolvedID: ${resolvedID}`,
        )
        return resolvedID
      },
    }
```

When I turn on the hash route, I go to the `http://127.0.0.1:5000/#/home` page.

I expected the result to be `http://127.0.0.1:5000/vue-2_6_14-dev.js`. What I actually saw was `http://127.0.0.1:5000/#/vue-2_6_14-dev.js`. The complete output is as follows:

```
id: vue
parentUrl: http://127.0.0.1:5000/src/bootstrap.ts
baseUrl: http://127.0.0.1:5000
resolvedID: http://127.0.0.1:5000/#/vue-2_6_14-dev.js
```

When I turn on the hash route, I go to the `http://127.0.0.1:5000/#/api/home` page.

I expected the result to be `http://127.0.0.1:5000/vue-2_6_14-dev.js`. What I actually saw was `http://127.0.0.1:5000/#/api/vue-2_6_14-dev.js`. The complete output is as follows:

```
id: vue
parentUrl: http://127.0.0.1:5000/src/bootstrap.ts
baseUrl: http://127.0.0.1:5000
resolvedID: http://127.0.0.1:5000/#/api/vue-2_6_14-dev.js
```

**Comment by guybedford** [comment]
Can you clarify what the problem is here? What are you expecting that is not happening?

**Comment by He110te4m** [comment]
I am very sorry for not describing my problem clearly. Now I have corrected the description.

**Comment by guybedford** [comment]
Agreed this is a bug, we use an optimized resolver to avoid the performance cost of using `new URL`.

Would you be interested in working on a fix?

**Comment by He110te4m** [comment]
I'm still trying to pinpoint the problem.
So far it seems that the resolveIfNotPlainOrUrl function, which gets segmented, has a problem.
I get a printout of `#/api/./_vue_composition_api-1_7_1-dev.js` , which is obviously not a legal value

**Comment by He110te4m** [comment]
As of now, when parsing pathname, parsing for non-file protocols is too easy.
In fact, `parentUrl` may contain hash routing, which is not considered when parsing.

**Comment by He110te4m** [comment]
@guybedford Maybe we could just add a line [here](https://github.com/guybedford/es-module-shims/blob/main/src/resolve.js#L46) to remove the hash in `parentUrl`.

Like this: `parentUrl.slice(0, parentUrl.indexOf('#'))`

**Comment by He110te4m** [comment]
@guybedford 

I'm sorry, that's my problem.

The package for the NPM I used is not updated and has been fixed in the latest version.

After I update the version, the function is normal.

I'm sorry again for wasting all this time.

**Comment by guybedford** [comment]
Glad you resolved the issue!
