### ISSUE TITLE
there should be less require property

### ISSUE THREAD

**Issue by loynoir** [guybedford/es-module-shims#382]
Extra require property, like `enforceIntegrity`

https://github.com/guybedford/es-module-shims/blob/main/index.d.ts#L19

**Comment by guybedford** [comment]
I'm sorry I don't understand the request?

**Comment by loynoir** [comment]
For example

https://github.com/guybedford/es-module-shims#polyfill-features

```html
<script>
window.esmsInitOptions = { polyfillEnable: ['css-modules', 'json-modules'] }
</script>
```

Seems like `window.esmsInitOptions = {}` is valid, right?

If so

- Actual: `enforceIntegrity: boolean`, means `esmsInitOptions` must have property `enforceIntegrity`.

- Expect:  `enforceIntegrity?: boolean`, means `esmsInitOptions` may not property `enforceIntegrity`, if have, its value should be nullish or boolean.
