### ISSUE TITLE
mismatch between code and type

### ISSUE THREAD

**Issue by loynoir** [guybedford/es-module-shims#384]
https://github.com/guybedford/es-module-shims/blob/1.8.0/index.d.ts#L52

dts say `skip` is `RegExp`.

https://github.com/guybedford/es-module-shims/blob/1.8.0/src/env.js#L51-L59

But the js code treat it like `RegExp | Array<string> | string`

Is it inaccurate type?

Or, is it the wasm implement is using that type?

**Comment by guybedford** [comment]
We should probably fix the JS code to support an explicit regexp, by doing an instanceof check I think?
