### ISSUE TITLE
Error using importShim in safari "Unhandled Promise Rejection: SyntaxError: Unexpected token '{'"

### ISSUE THREAD

**Issue by jogibear9988** [guybedford/es-module-shims#387]
See the function wich fails:

<img width="1444" alt="image" src="https://github.com/guybedford/es-module-shims/assets/364896/95716142-b4ab-44d3-9254-a49c6b575722">

Safari: Version 16.2 (18614.3.7.1.5)

**Comment by jogibear9988** [comment]
In safari Tech preview: Release 160 (Safari 16.4, WebKit 18615.1.14.3)
it works

**Comment by guybedford** [comment]
Thanks for posting. Unfortunately I don't have Safari 16.4 installed anywhere myself. This is the code path that does the main evaluation, so it sounds like this is a code / syntax error in the underlying codebase. I would check the `url` being executed there (`load.u`) and verify the source is correct. You can also check the `load.b` value then search for that blob URL in the sources panel.

The important thing here would be to determine the source causing the syntax error which would be determined from the above. Alternatively you can log the main `.source` creation function along with the `load.u` value to determine which source is being generated for which URL.

Safari error messages aren't great unfortunately, but I suspect it is most likely a genuine syntax error.

**Comment by jogibear9988** [comment]
I thought of that, but I didn't find an error in the loaded file...
It also works in Chrome, and Firefox...
I thought maybe an "import" wich maybe still has an assert, but I did not find anything, maybe I'll try commenting out code

**Comment by jogibear9988** [comment]
Found it,

I compile to ES2022, and Typescript created a static initialization block in 2 files (even if I did not use them in typescript code). This is not yet supported in this safari version.

I did find it now using an old version of firefox, I tried a few versions till 90 did break.
The advantage of firefox is, it shows such errors. In chrome to find an error in the import chain, is the same bullshit as in webkit.
see also: https://bugs.chromium.org/p/chromium/issues/detail?id=954770&q=&can=4

**Comment by guybedford** [comment]
Yeah Safari just is particularly bad here unfortunately. Have to be extra careful with modern syntax. I've experimented a bunch with errors, and the current error does actually give a hint stack if you expand it I believe, it's just hard to see in the error message.
