### ISSUE TITLE
Custom fetch hook function seems to just 'stop executing' in some cases (when the function takes a long time to complete)

### ISSUE THREAD

**Issue by zachsa** [guybedford/es-module-shims#394]
Using this `fetch` hook:

```js
globalThis.esmsInitOptions = {
  shimMode: true,
  async fetch(url, options) {
    const res = await fetch(url, options)
    if (!res.ok) return res
    const isImportMapFile = url.endsWith('importmap') || url.endsWith('importmap.json')
    const isSameOrigin = url.includes(globalThis.origin)
    if (!isImportMapFile && isSameOrigin) {
      const source = await res.text()
      const transformed = await transpile({ url, source })
      console.log(url, 'done')
      return new Response(new Blob([transformed], { type: 'application/javascript' }))
    }
    return res
  },
  ...
}
```

I am finding that I can `await transpile(...)`, and that works okay. For example, this works:

```js
async function transpile({ url, source, filename = undefined }) {
  try {
    return new Promise((resolve, reject) => {
      filename = filename || path.basename(new URL(url).pathname)
      const transformed = transform(source, {
        filename: ['.tsx', '.ts', '.js', '.jsx'].some(ext => filename.endsWith(ext))
          ? filename
          : undefined,
        presets: [presetReact, presetTypescript],
      })
      resolve(transformed.code)
    })
  } catch (e) {
    console.error(e)
    throw e
  }
}
```

However within the awaited `transpile` function, it seems if it takes too long to complete, then it seems like the fetch hook just fails. For example:

_**This works**_
```js
async function transpile({ url, source, filename = undefined }) {
  try {
    await new Promise(r => setTimeout(r, 0))
    ... rest of function
```

_**This also still works**_
```js
async function transpile({ url, source, filename = undefined }) {
  try {
    await new Promise(r => setTimeout(r, 100))
    ... rest of function
```

_**But this doesn't work**_
```js
async function transpile({ url, source, filename = undefined }) {
  try {
    await new Promise(r => setTimeout(r, 750))
    ... rest of function
```

The 'done' in the `fetch` hook is never logged, and the `catch` in the transpile function isn't reached either. I don't know if I'm doing something wrong, but it seems that if I am I should recieve an error of some kind. Otherwise, what can cause the `fetch` hook to just seemingly stop executing if it takes a long time to complete?

**Comment by guybedford** [comment]
It sounds like you're hitting connection idle timeouts? Have you tried sending whitespace as a way to keep the connection open under a threshold?

**Comment by zachsa** [comment]
That sounds likely, but should I not at least see a failed request? There is no entry in the network tab that corresponds to the failed requests / or console log.

I'm not sure how I would send whitespace from the get request to keep the connection open?

(thank you for the response)

**Comment by zachsa** [comment]
It's the 'transformed
```js
const transformed = await transpile({ url, source })
return new Response(new Blob([transformed], { type: 'application/javascript' }))
```

**Comment by zachsa** [comment]
Here is the issue:

```js
async function transpile(source) {
  await new Promise(res => setTimeout(res, 1000))
  return new Promise(res => res(babel.transform(source)))
}

// First setup es-module-shims with custom fetch hook

// Then collect scripts of type="esm-x", and transpile them
document.addEventListener('DOMContentLoaded', async () => {
  const scripts = document.querySelectorAll('script[type="esm-x"]')
  for (script of scripts) { await transpile(script.innerHTML) }
})
```

All the imports originate from the transpiled `esm-x` scripts. If I don't include the pause in the transpile function then everything works (i.e. the imports defined in the script tags as innerHTML is transpiled, and then the fetch hook is called to resolve imports ). But if I do include the pause in the transpile function, then the imports defined in the custom esm-x scripts are seemingly discarded

**Comment by guybedford** [comment]
Ahh, you're injecting module scripts and if you inject scripts after the dom ready of the page they aren't executed per standard HTML semantics.

Therefore you need to generate a new `<script type="module-shim">` set its innerHTML, and dynamically add it to the HEAD. es-module-shims will pick it up as it listens to the mutator events.

**Comment by zachsa** [comment]
Okay - thank you.

Specifically is it it important to inject a new script (as opposed to just changing the type attribute of an existing script), and does it have to be in the head?

**Comment by guybedford** [comment]
Yes and no.

**Comment by zachsa** [comment]
Okay. noted - one last question on this thread. I'm noticing that the `DOMContentLoaded` event is fired twice unless I use `{ once: true }`. Is this related to es-module-shims?

**Comment by guybedford** [comment]
https://github.com/guybedford/es-module-shims#no-load-event-retriggers
