### ISSUE TITLE
Discussion: Minified js build

### ISSUE THREAD

**Issue by corebsp** [guybedford/es-module-shims#395]
I notice that in the earlier builds that a minified build was available, but that this has been removed in a later build and is not part of the current rollup config.

Is there a reason why a minified version should not be used? Was there a problem caused by terser?

**Comment by guybedford** [comment]
The argument here is that publishing minified files to npm is unnecessary when firstly minification is a relatively minor optimization over compression and module CDNs should handle minification anyway.
