### ISSUE TITLE
CSS modules support

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-shims#40]
We just implemented CSS modules in SystemJS via https://github.com/systemjs/systemjs/pull/1997. It could be worthwhile to provide a similar implementation here.

//cc @justinfagnani

**Comment by LarsDenBakker** [comment]
I think it would be a massive benefit if we can shim upcoming module types here. Are there currently hooks for setting this up easily? Would this add a lot of extra overhead to do at runtime?

**Comment by guybedford** [comment]
I've put together an implementation in #41.

**Comment by guybedford** [comment]
Released in 0.3.0
