### ISSUE TITLE
Default example script URL is leading to 404

### ISSUE THREAD

**Issue by gryzzly** [guybedford/es-module-shims#415]
Hey, when trying to follow the example the URL for the script is leading to 404 –
https://ga.jspm.io/npm:es-module-shims@1.9.0/dist/es-module-shims.js

**Comment by gryzzly** [comment]
I managed to get it via esm – 
```
<script async type="module" src="https://esm.sh/es-module-shims@1.9.0"></script>
```

**Comment by guybedford** [comment]
Thanks, this is working now.
