### ISSUE TITLE
Import SHim generates wrong code....

### ISSUE THREAD

**Issue by jogibear9988** [guybedford/es-module-shims#419]
I've a ffile wich looks like this:

                        return {
                            element: new mfcSimulation.MfcSimulation(service, plant),
                        };
                    case MfcViews.ActionsDesigner:
                        import('../components/mfc/mfc-actions-designer.js');
                        return {
                            element: new GenericTableViewBuilder(MfcActionCombinedDTO)
                                .setServiceName(service.Name)
                                .setTitle(title)
                                .setTableViewExtension(new MfcActionGridControls())
                                .setDetailsControl(MfcActionsDesigner.is)
                                .setDetailsInTab(true)
                                .build()
                        };
                    case MfcViews.LiveView:
                    .....
                    case WmsViews.ActionsDesigner:
                        import('../components/wms/wms-actions-designer.js');
                        return {
                            element: new GenericTableViewBuilder(BasicActionDTO)
                                .setService(ServiceType.WMSService)
                                .setTitle(title)
                                .setDetailsControl('wms-actions-designer')
                                .setDetailsInTab(true)
                                .build()
                        };
                    case WmsViews.Hardware:

after import shim it looks like this (in chrome source tab):

                        return {
                            element: new mfcSimulation.MfcSimulation(service, plant),
                        };
                    case MfcViews.ActionsDesigner:
                        importShim('../components/mfc/mfc-actions-designer.js', 'http://127.0.0.1:8088/dist/view/viewCreator.js');
                        return {
                            element: new GenericTableViewBuilder(MfcActionCombinedDTO)
                                .setServiceName(service.Name)
                                .setTitle(title)
                                .setTableViewExtension(new MfcActionGridControls())
                                .setDetailsControl(MfcActionsDesigner.is)
                                .setDetailsInTab(true)
                                .build()
                        };
                    case MfcViews.LiveView:
                    .....
                    case WmsViews.ActionsDesigner:
                        importShim(
     ;import{u$_}from'blob:http://127.0.0.1:8088/aecf5795-7472-4cac-9778-e71f4d74817e';try{u$_({ViewCreator:ViewCreator})}catch(_){};
    '../components/wms/wms-actions-designer.js', 'http://127.0.0.1:8088/dist/view/viewCreator.js');
                        return {
                            element: new GenericTableViewBuilder(BasicActionDTO)
                                .setService(ServiceType.WMSService)
                                .setTitle(title)
                                .setDetailsControl('wms-actions-designer')
                                .setDetailsInTab(true)
                                .build()
                        };
                    case WmsViews.Hardware:

means, the second import is rewritten in a wrong way. Any Idea what I do wrong, or if there could be an error in your code?

**Comment by jogibear9988** [comment]
I fixed it by moving this line:

https://github.com/guybedford/es-module-shims/blob/f24d23f96e42728546d49991278829936f7c9e59/src/es-module-shims.js#L351

one down (means after the if)

**Comment by jogibear9988** [comment]
It seems, to load, but some imports do not work after my change

**Comment by jogibear9988** [comment]
It works if I insert this lines:

          if (load.s && resolvedSource.endsWith("importShim("))
            load.s=undefined;

before here:

https://github.com/guybedford/es-module-shims/blob/f24d23f96e42728546d49991278829936f7c9e59/src/es-module-shims.js#L254

This for sure is a very dirty hack.

**Comment by guybedford** [comment]
Thanks for reporting this issue, I believe https://github.com/guybedford/es-module-shims/pull/421 should a correct fix for this.

If you're able to verify that change in your app that would be a great help to know.

**Comment by jogibear9988** [comment]
I can confirm it works with this change.

Could you create a new package?
