### ISSUE TITLE
Top level await

### ISSUE THREAD

**Issue by littledan** [guybedford/es-module-shims#5]
Would it make sense to implement top-level await within this project? It can be accurately simulated by exporting a Promise from each module, and waiting on Promise.all of these exports.

**Comment by guybedford** [comment]
@littledan yes that is not only useful, but necessary to fix the WASM 4KB limit as well.

I'd be keen to work on this if top-level await is looking likely to proceed.

**Comment by guybedford** [comment]
See https://github.com/guybedford/es-module-shims/issues/1#issuecomment-453785226.

**Comment by littledan** [comment]
I hope we can clarify things soon, e.g., at an upcoming TC39 meeting. In theory, Stage 2 should mean it's eventually coming, though.

**Comment by littledan** [comment]
I hope we can clarify things soon, e.g., at an upcoming TC39 meeting. In theory, Stage 2 should mean it's eventually coming, though.

**Comment by guybedford** [comment]
I've been putting some thought to how this might be implemented.

Proposed outline:

- We can detect the use of top-level await based on the "await" keyword being seen at the top-level. Supporting "await" within blocks would require a knowledge of functions v blocks, but that should be straightforward to handle too.
- When a source has top-level await, we know where all the import and export statements start and end so we could hoist them all up to the top of the source together. class / function / variable declarations would need to be converted into their non-export form in this process, with some careful handling of these cases.
- The remaining body can then be wrapped in an `async` wrapper, with the execution exported as a special unique export name (like `__$$tla` or something).
- the rest of the process is then just handling the TLA algorithm

The above would be a comprehensive and fast top-level await polyfill!

I don't have the resources to work on this right now, but if anyone would like to push things forward I'd be very open to sponsorship for this.

**Comment by MathiasWP** [comment]
Any updates on this issue?

**Comment by guybedford** [comment]
None currently but it remains a core part of the roadmap of this project. The problem is just one of prioritization.

**Comment by trusktr** [comment]
No one mentioned it, but just in case, Node.js already has built-in top-level await.

**Comment by guybedford** [comment]
Top-level await was shipped so quickly by browsers that it has ended up not being a problem for this project.
