### ISSUE TITLE
application/x-javascript throws error

### ISSUE THREAD

**Issue by costingeana** [guybedford/es-module-shims#54]
This may be related to #52. Some servers may also return content-type 'application/x-javascript' or 'text/x-javascript'; these values are specified in the HTML standard: https://mimesniff.spec.whatwg.org/#javascript-mime-type.

Should we support these values?

**Comment by guybedford** [comment]
Are you specifically using servers with this support that it would be useful for? Yes in theory we should support all the MIMEs, but we should also aim for practicality, where the important point is covering supporting all the servers.

**Comment by guybedford** [comment]
Released in 0.4.2.
