### ISSUE TITLE
[Question] Code transformation when importing

### ISSUE THREAD

**Issue by zaygraveyard** [guybedford/es-module-shims#59]
I'm trying to create a loader for [theintern/intern](https://github.com/theintern/intern) that supports ES modules and [power-assert-js/power-assert](https://github.com/power-assert-js/power-assert)

I got it working fantastically with ES modules using this library
But when trying to add a transformation step in the loader to transform the modules using [power-assert-js/espower-source](https://github.com/power-assert-js/espower-source), I ran into the problem that I can't `import()` a module from source (using blob URLs) unless it doesn't import any other module.

Does anyone have an idea this might be done?
Any pointers are much appreciated

---
#### Update
Gist for the ES module shims loader: https://gist.github.com/zaygraveyard/ae6cc847663fdc3898e51303f1c5a66d

**Comment by zaygraveyard** [comment]
I managed to do it by monkey-patching `fetch()` to return the transformed code (very ugly hack, I know)
Still looking for better cleaner solutions

PS: I have yet to transform the code itself with [power-assert-js/espower-source](https://github.com/power-assert-js/espower-source)

**Comment by guybedford** [comment]
Because modules load relative to their parent modules, when using a Blob URL the imports need to be remapped as well.

**Comment by guybedford** [comment]
To clarify - basically the imports need to be full URLs when using blob URLs.

**Comment by zaygraveyard** [comment]
Good point, but unfortunately it's not strait-forward to remap all the imported URLs in the source to absolute ones.

Can an import map fix this?

**Comment by guybedford** [comment]
Actually, yes, an import map would be able to handle this certainly.

**Comment by zaygraveyard** [comment]
It works but not in the way I expected
An absolute URL imported from a blob, example `'/src/index.js'` get resolved to `'blob/src/index.js'` before lookup in the import map
And a relative URL imported from a blob, example `'../src/index.js'` get resolved to `'blob:src/index.js'` before lookup in the import map

**Comment by guybedford** [comment]
It should be a full URL - `https://site.com/...`.

Import maps will work for URLs though so you can map `"blob/": "https://site.come/"` as a single mapping in the import map and have them all work out!

**Comment by guybedford** [comment]
(although the problem remains that dependency transformations are not possible under this model)

**Comment by zaygraveyard** [comment]
> It should be a full URL - `https://site.com/...`.
> 
> Import maps will work for URLs though so you can map `"blob:src/": "https://site.com/src/"` as a single mapping in the import map and have them all work out!

I know, that's why I said it works :wink: 
But I'm not sure if that's the way it should work (I haven't yet tested in chrome to see what happens)
Plus there's an inconsistency between the absolute paths and the relative ones (they get resolved to `blob/...` and `blob:...` respectively)

**Comment by guybedford** [comment]
> Plus there's an inconsistency between the absolute paths and the relative ones (they get resolved to blob/... and blob:... respectively)

Interesting... that is a bug! Posted https://github.com/guybedford/es-module-shims/issues/61.

Yes the same approach should work in Chrome as we implement import maps the same!

**Comment by zaygraveyard** [comment]
> Yes the same approach should work in Chrome as we implement import maps the same!

I mean natively, since Chrome supports import maps

**Comment by zaygraveyard** [comment]
It doesn't look like Chrome supports using import maps to resolve import URLs in blobs
Only full URL work in blobs :cry:

**Comment by guybedford** [comment]
I think the reason for this is likely that `new URL('/asdf', 'blob:asdf')` actually throws an error in the URL resolver. I've corrected the info at #61.

**Comment by zaygraveyard** [comment]
Current solution is somthing like this:
```js
const res = await fetch(url);
const baseUrl = new URL(res.url || url, document.baseURI);
const contentType = res.headers.get('content-type');
const source = (
  await transform(await res.text())
    .replace(/(import\s+(?:[^;]*\s+from\s+)?['"])(.+)(['"](?:;|$))/mg, importUrlReplacer)
    .replace(/(import\s+\(\s+['"])(.+)(['"]\))/mg, importUrlReplacer)
);
const blob = new Blob([source], {type: contentType});
return window.importShim(URL.createObjectURL(blob));

function importUrlReplacer(match, p1, p2, p3) {
  return `${p1}${new URL(p2, baseUrl)}${p3}`;
}
```

I'm sure this RegExp solution doesn't handle all the cases but I guess it can be replaced with an implementation based on [es-module-lexer](https://github.com/guybedford/es-module-lexer)

**Comment by zaygraveyard** [comment]
Or manipulating the AST in the transform function

**Comment by guybedford** [comment]
I finally went ahead and opened up a `fetch` hook for this project. The PR at https://github.com/guybedford/es-module-shims/pull/73 includes an example in the readme of how custom source transforms might work. The benefit here is not needing to do the import statement regexes as this project already provides that replacement process in a fully JS-compliant way via wasm.

@zaygraveyard do try it out if you can, will close this otherwise, although the release is still pending.
