### ISSUE TITLE
Mixed Content security error for 'std:kv-storage'

### ISSUE THREAD

**Issue by metafeather** [guybedford/es-module-shims#60]
Browser: Google Chrome on MacOS 10.14.6 - Version 76.0.3809.132 (Official Build) (64-bit)

Including https://unpkg.com/es-module-shims@0.4.1/dist/es-module-shims.js in an html page running under HTTPS results in a security error:

```
Mixed Content: The page at 'https://my-domain/test.html' was loaded over HTTPS, but requested an insecure script 'std:kv-storage'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by guybedford** [comment]
This is the way in which builtin support is being performed by the loader, and the errors don't have any affect on the running functioning of the page.

I certainly agree though it would be nicer if we could avoid them somehow, and there might well be approaches. Will leave this open to track that.

**Comment by guybedford** [comment]
I've switched this detection to happen lazily so that the console errors are avoided unless you explicitly load kv-storage. https://github.com/guybedford/es-module-shims/pull/62

**Comment by MicahZoltu** [comment]
In chrome I'm getting a similar, but not the same error:
```
GET std:kv-storage net::ERR_UNKNOWN_URL_SCHEME
(anonymous) | @ | VM34:1
(anonymous) | @ | es-module-shims.js:487
...
```
Will this also be fixed when #62 is released, or is it something different?

**Comment by vedtam** [comment]
@MicahZoltu having the same error

![Screen Shot 2019-09-08 at 10 25 07](https://user-images.githubusercontent.com/4981592/64484996-f86b1880-d222-11e9-9e36-4f8b0469dad7.png)

**Comment by vedtam** [comment]
here's a demo throwing the very first error (plain, fresh project):
https://vedtam-pika-demo.glitch.me

and the source (you may need to open the console to get to './web_modules':
https://glitch.com/edit/#!/vedtam-pika-demo?path=index.html:10:25

**Comment by guybedford** [comment]
0.4.3 released with the fix.

**Comment by vedtam** [comment]
@guybedford thanks! In the meantime I figured it out that the second throw is "expected", as it may be for a feature detect.
