### ISSUE TITLE
Regression in v0.4.3?

### ISSUE THREAD

**Issue by zaygraveyard** [guybedford/es-module-shims#63]
When I updated to the latest version v0.4.3, I ran into the same (or very similar) bug as guybedford/es-module-lexer#34
In v0.4.2 I didn't have this issue

You can try it here https://jsfiddle.net/s9hk15tm/1/
Check out the browser's console for errors

And I tried to parse the same code in the lexer directly, and found that it parses it fine.
So I don't know what happened

**Comment by guybedford** [comment]
Thanks, yes it was built against the wrong es-module-lexer version (previous version). I've corrected this and published a 0.4.4.
