### ISSUE TITLE
Edge 16

### ISSUE THREAD

**Issue by jonbjk** [guybedford/es-module-shims#68]
Hi
According to https://github.com/guybedford/es-module-shims#browser-compatibility-with-es-module-shims es-module-shims should work for Edge 16+. However, we have are getting errors for Edge 16.
I tried tried the tests in this project, but they do not work at all with Edge 16.
The situation is cumbersome for us.
In our own project we use a <script type="module"> / <script nomodule> pattern to switch between using es-module-shims for modern browsers and a SystemJs fallback for older browsers.
The problem is that this "switching" pattern identifies Edge 16 as a modern browser but es-module-shims does not work.
Does anyone else have problems with Edge 16?

**Comment by just-dont** [comment]
I tried to run my stuff in Edge and I'm seeing no indication that the type="module-shim" code even loads at all.

**Comment by chase-moskal** [comment]
yes, i can confirm these results via browserstack on windows 10 at url https://chasemoskal.com/menutown/

- **edge 18:** :heavy_check_mark: es-module-shims works
- **edge 17:** :heavy_check_mark: es-module-shims works
- **edge 16:** :x: es-module-shims appears to fail  
    no console errors reported,  
    network tab shows 200 ok's for the import-mapped npm modules from jsdelivr,  
    module-shim code doesn't seem to execute  
- **edge 15:** :x: es-module-shims fails
    ```
    SCRIPT5009: 'WebAssembly' is undefined
    es-module-shims.js (240,605)
    ```

**Comment by jonbjk** [comment]
That it fails in Edge 15 is expected, since Edge 15, to my knowledge, does not support es-modules at all.
But it should work in Edge 16.

**Comment by gingur** [comment]
I'm getting an error on edge18 (Microsoft EdgeHTML 18.19042) due to the es-module-lexer catch syntax, it expects a `()`

**Comment by guybedford** [comment]
I've updated the compat to note we support Edge 17+ instead in https://github.com/guybedford/es-module-shims/pull/178.
