### ISSUE TITLE
Duplicate requests

### ISSUE THREAD

**Issue by bahrus** [guybedford/es-module-shims#69]
If I create two imports in my source file:

```JavaScript
import  "@ui5/webcomponents/dist/Input.js";
import "@ui5/webcomponents/dist/TextArea.js";
```

with import map:

```html
        <script type="importmap-shim">
        {
            "imports": {
                "@ui5/": "https://storage.googleapis.com/pika-web-packages-02/ui5-buffet/0.0.0/dist-es2019/ui5-buffet.min.js#"
             }
       }

```

My intention (admittedly a bit of a hack) is to allow the import mapping to allow multiple references to point to the same bundled file.  In theory, appending anything after the hash shouldn't cause that part of the string to be passed to the server.

What I'm seeing is that two identical requests are getting sent to the server.  Only one should be necessary, I'm thinking?

**Comment by bahrus** [comment]
Actually, it seems that

1.  How es-module-shims behaves changed with a newer version
2.  The behavior of the newer version has the same effect as what [Chrome 77 currently does](https://github.com/WICG/import-maps/issues/185), which is to block the hack from working.

**Comment by bahrus** [comment]
Actually, version 2:

With the newer version of es-module-shims, this mapping works the same way as the older version of es-module-shims:  unlike Chrome 77, it resolves as I would it expect it to resolve, but it does so by mapping two duplicate requests.

"@ui5/": "https://storage.googleapis.com/pika-web-packages-02/ui5-buffet/0.0.0/dist-es2019/ui5-buffet.min.js#/",

Chrome 77 throws away the last part of the url, ui5-buffet.min.js, which I wish it wouldn't do.

**Comment by guybedford** [comment]
Thanks for investigating these cases, I've created https://github.com/guybedford/es-module-shims/issues/70 to ensure we follow the exact normalization behaviours.

We do have to follow what the spec does, with some lee-way for stability though (that thread is a relatively recent change).
