### ISSUE TITLE
Proposal: An experimental depcache implementation

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-shims#77]
I recently opened this issue on the import maps specification to again discuss handling the waterfall problem of module loading - https://github.com/WICG/import-maps/issues/208.

### Problem

It is common in npm workflows to possibly have dependency trees with depths of up to 10 modules deep.

Import maps bring these kinds of workflows to the browser, where unlike other resources which typically cap out at 2-3 extra round trips of latency (eg page.html -> style.css -> common.css -> header.png). There's a natural upper bound for most resources because there aren't really development patterns that increase the depth here.

But with modules, the depth in theory can have no limit. 10 extra round trips becomes a second of latency in some areas. If we get to depths of 20 / 30 modules in a tree, that becomes worse even with geographic edge caching.

### Proposal

SystemJS successfully solved this problem a long time ago with depcache, and it can map to import maps quite easily.

The concept is that the import map is generated by some tool on the server that knows about all the modules. So that tool can also inject what is called a "dependency cache". Basically just letting the system know what imports each module has.

_This information is enough to flatten the full tree and request all modules in parallel._

The suggested semantics are the following:

```html
<script type="importmap">
{
  // standard import map properties
  "imports": { ...imports... },
  "scopes": { ...scopes... }

  // proposed property:
  "depcache": {
    "/module.js": [
       "pkgimport",
       "./relimport.js",
       "//url.com/import.js"
    ],
    "/module2.js": [...]
  }
}
</script>
```

This proposal works well with dynamic import and lazy loading - if `/module2.js` is lazily imported dynamically (say a plugin system), then since we already know all its dependencies upfront we can download them in parallel.

Given that import maps aren't driving any work on this, and I've tried unsuccessfully over the past year to engage specification authors on working on a solution to this problem, it may be time to just implement the solution in es-module-shims.

This will provide the feature and benefits to users.

At the same time, a specification for depcache can be brought to the import maps spec, and whatever that turns into having this experimental feature in es-module-shims can help drive the process.

Further suggestions / thoughts on the above very welcome, otherwise I think the time has come to make a move here.

**Comment by guybedford** [comment]
Implemented in https://github.com/guybedford/es-module-shims/pull/78.

**Comment by SunHuawei** [comment]
This deserves a sentence in README.md or some doc.

**Comment by guybedford** [comment]
@SunHuawei `<link rel="modulepreload">` inlining each full URL that would be in the depcache is basically the way to do this now. `depcache` made no progress as a spec. That is, we have a good static preloading story, albeit with HTML injection, and no dynamic preloading story for modules.

**Comment by SunHuawei** [comment]
@guybedford, thanks for your information. Static preloading is useful. However, `depcache` and dynamic preloading are useful, too. Not sure why `depcache` is not included in the spec, but it's definitely a wrong decision.
