### ISSUE TITLE
File extensions....

### ISSUE THREAD

**Issue by Hypercubed** [guybedford/es-module-shims#8]
In the import-map proposal there is a note regarding file extenions:

> Note how unlike some Node.js usages, we include the ending .js here. File extensions are required in browsers; unlike in Node, we do not have the luxury of trying multiple file extensions until we find a good match. Fortunately, including file extensions also works in Node.js; that is, if everyone uses file extensions for submodules, their code will work in both environments.

Is there any way to set a default extension planned either in the spec or in this shim?  Without it many es6 modules will not work as they are.  We would need to explicitly add each in the import map:

```json
{
  "imports": {
    "lit-html": "/dist/pkg/lit-html@1.0.0/lit-html.js",
    "lit-html/": "/dist/pkg/lit-html@1.0.0/",
    "lit-html/lit-html": "/dist/pkg/lit-html@1.0.0/lit-html.js",
    "lit-html/lib/shady-render": "/dist/pkg/lit-html@1.0.0/lib/shady-render.js",
  }
}
```

**Comment by guybedford** [comment]
No, there is no default extension mechanism at all, so extensions are needed always, like you have above.

This won't change, so best to just get used to it at this point!

Note that for example, in Node.js we are looking at removing support for automatic file extensions to try and encourage this approach.
