### ISSUE TITLE
Proposal: Pre-url map lookup handling

### ISSUE THREAD

**Issue by AndersMad** [guybedford/es-module-shims#80]
I know it's against the "standard" - but just like the `fetch` handle - to have a method called before (or after) map lookup. 

Situation 1: Package name is "always" e.g. "some path" + module name + "/dist/index.es.js" 

Situation 2: "framework-x" where x is 20 modules - instead of 20 map lines (or code that generates them - may not know them all) - have some logic about it: if url starts with then return that else this.

It's only 2 lines i spose.

**Comment by guybedford** [comment]
There are a few options here:

1. Generate the map itself dynamically, then inject it into the HTML page with some script. This works both for native import maps and should work for this project, and allows the map itself to be "generated" at runtime. It still requires the entire map itself to be generated though.
2. Have a hook when requesting a bare specifier that is not located in the import map. This would effectively act like a sort of "install" hook, and I have discussed bringing this up as a native spec before. Any work here should be done alongside some efforts at the standards level, but I think it might be something the browser could consider supporting - eg `document.addEventListener('importmapresolvefallback', (specifier, parent) => return getUpdatedImportMap)` or something like that.
3. Have a fully custom hook that acts as a way to intercept the import map process.

I would suggest you try (1) as much as possible here first, to find out if you are truly hitting these limits.

Then (2) and (3) are similar, but I think should be a feature discussion based on why these limits need to be pushed, and if that justification is strong enough it should also be strong enough to argue for standards efforts here too.

**Comment by AndersMad** [comment]
Thanks for the details! I hope it makes it into the standard.

The "problem" about (1) is that it is not dynamic enough - it still has to know the names + know them before load - so when adding a new module in a dynamic environment - one will have to maintain the loader too. The fallback to me sounds like the best option because the map will always take precedence.

**Comment by guybedford** [comment]
Yes I would definitely like to see us work on a hook for (2) and even created https://github.com/guybedford/import-maps-extensions with this in mind too. Whether we can build support for this approach in WICG is yet to be seen though. The "package lookup" hook is an idea to keep seeding to browser vendors though :)
