### ISSUE TITLE
Relative URLs specifiers

### ISSUE THREAD

**Issue by nestarz** [guybedford/es-module-shims#82]
When I try to map from a relative URLs specifier, the specifier is resolved, then it does not remap `./src/foo.js` to `./dist/foo.js`.

import-map.json (located in an arbitrary subfolder)

```
{
    "imports": {
        "./src/foo.js": "./dist/foo.js",
    }
}
```

index.js
```
import "./src/foo.js"
```

**Comment by guybedford** [comment]
The above should map any import to `https://webroot.com/src/foo.js` (relative or exact URL) to `https://webroot.com/dist/foo.js`.

If your file is located at `https://webroot.com/app/src/foo.js` then it won't be mapped, unless you use eg a `<base>` tag to change the baseURL to the subfolder.
