### ISSUE TITLE
Infinite recursion between processScripts and topLevelLoad if no import map defined

### ISSUE THREAD

**Issue by Legioth** [guybedford/es-module-shims#86]
If no `importmap-shim` tag exists but there is at least one `module-shim` tag, then the bootstrap logic will go into infinite recursion between `processScripts` and `topLevelLoad`. Adding a minimal (i.e. containing only `{}`) `importmap-shim` tag before the first `module-shim` will suppress the problem.

Can be reproduced with version 0.5.0 with this minimalistic HTML and an empty `index.js` file.
```
<!DOCTYPE html>
<html>
<head>
  <script src="./es-module-shims.js"></script>
  <script type="module-shim" src="./index.js"></script>
</head>
</html>

```

**Comment by guybedford** [comment]
Thanks for posting, published the fix in 0.5.1.
