### ISSUE TITLE
Support a resolve hook

### ISSUE THREAD

**Issue by gingur** [guybedford/es-module-shims#94]
Was wondering if it would be worth moving importMap support to a plugin, so it's considered optional? I have some ideas that don't align with the current importMap spec, and so want to replace it entirely with a different solution but hoping to ship w/out the extra bytes.

**Comment by guybedford** [comment]
Are you sure the problem here is the file size impact of having import maps included?

The code for import maps in this project is not even 100 lines, minified it is really not a bloat problem.

Perhaps the focus here rather should be on ensuring the resolver hook can be properly exposed to add customizations?

**Comment by gingur** [comment]
yeah, it depends on how robust you want to make the interface. in its current state, I'm unable to do much for my use cases, but moving importMap to a plugin would most likely open up things and expose critical utils needed.

for what it's worth, I was able to get a node implementation working, as well introduce some interesting preprocessing optimizations around the importMap definition by using your source with minimal changes. my hope would be to apply similar functionality as a plugin, instead of having to completely fork the project.

**Comment by guybedford** [comment]
I would be happy to take a PR to this project that renames the internal `resolve` calls to instead call a `importShim.resolve` function which is the import maps etc implementation by default. That way this could then be hooked with custom changes more easily.

Happy to discuss the outline of the above further if that interests you.

If you'd consider wanting to upstream the Node.js support that is certainly something I'd be open to taking a PR for here as well.

**Comment by gingur** [comment]
Sure, I can take a crack at it.

**Comment by guybedford** [comment]
Great, let's start with the resolve hook, and if you're also interested in the node implementation to create a new issue to outline the approach there.

**Comment by guybedford** [comment]
This was implemented in https://github.com/guybedford/es-module-shims/pull/146.
